Deity.create([
  {:name => "Auril",
   :of => "Goddess of Winter",
   :alignment_id => 8,
   :image_id => '',
   :symbol => "Six-pointed snowflake",
   :realm_id => 1,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Azuth",
   :of => "God of Wizards",
   :alignment_id => 4,
   :image_id => '',
   :symbol => "Left hand pointing upward, outlined in fire",
   :realm_id => 1,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Bane",
   :of => "God of Tyranny",
   :alignment_id => 7,
   :image_id => '',
   :symbol => "Upright black right hand, thumb and fingers together",
   :realm_id => 1,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Beshaba",
   :of => "Goddess of Misfortune",
   :alignment_id => 9,
   :image_id => '',
   :symbol => "Black antlers",
   :realm_id => 1,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Bhaal",
   :of => "God of Murder",
   :alignment_id => 8,
   :image_id => '',
   :symbol => "Skull surrounded by a ring of blood droplets",
   :realm_id => 1,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Chauntea",
   :of => "Goddess of Agriculture",
   :alignment_id => 2,
   :image_id => '',
   :symbol => "Sheaf of grain or a blooming rose over grain",
   :realm_id => 1,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Cyric",
   :of => "God of Lies",
   :alignment_id => 9,
   :image_id => '',
   :symbol => "White jawless skull on black or purple sunburst",
   :realm_id => 1,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Deneir",
   :of => "God of Writing",
   :alignment_id => 2,
   :image_id => '',
   :symbol => "Lit candle above an open eye",
   :realm_id => 1,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Eldath",
   :of => "Goddess of Peace",
   :alignment_id => 2,
   :image_id => '',
   :symbol => "Waterfall plunging into a still pool",
   :realm_id => 1,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Gond",
   :of => "God of Craft",
   :alignment_id => 5,
   :image_id => '',
   :symbol => "Toothed cog with four spokes",
   :realm_id => 1,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Helm",
   :of => "God of Protection",
   :alignment_id => 4,
   :image_id => '',
   :symbol => "Staring eye on upright left gauntlet",
   :realm_id => 1,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Ilmater",
   :of => "God of Endurance",
   :alignment_id => 1,
   :image_id => '',
   :symbol => "Hand bounds at wrist with red cord",
   :realm_id => 1,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Kelemvor",
   :of => "God of the Dead",
   :alignment_id => 4,
   :image_id => '',
   :symbol => "Upright skeletal arm holding balanced scales",
   :realm_id => 1,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Lathander",
   :of => "God of Birth and Renewal",
   :alignment_id => 2,
   :image_id => '',
   :symbol => "Road traveling into a sunrise",
   :realm_id => 1,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Leira",
   :of => "Goddess of Illusion",
   :alignment_id => 9,
   :image_id => '',
   :symbol => "Point-down triangle containing a swirl of mist",
   :realm_id => 1,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Liira",
   :of => "Goddess of Joy",
   :alignment_id => 3,
   :image_id => '',
   :symbol => "Triangle of three six-pointed stars",
   :realm_id => 1,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Loviatar",
   :of => "Goddess of Pain",
   :alignment_id => 7,
   :image_id => '',
   :symbol => "Nine-tailed barbed scourge",
   :realm_id => 1,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Malar",
   :of => "God of the Hunt",
   :alignment_id => 9,
   :image_id => '',
   :symbol => "Clawed paw",
   :realm_id => 1,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Mask",
   :of => "God of Thieves",
   :alignment_id => 6,
   :image_id => '',
   :symbol => "Black mask",
   :realm_id => 1,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Mielikki",
   :of => "Goddess of Forests",
   :alignment_id => 2,
   :image_id => '',
   :symbol => "Unicorn's head",
   :realm_id => 1,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Milil",
   :of => "God of Poetry and Song",
   :alignment_id => 2,
   :image_id => '',
   :symbol => "Five-stringed harp made of leaves",
   :realm_id => 1,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Myrkul",
   :of => "God of Death",
   :alignment_id => 8,
   :image_id => '',
   :symbol => "White human skull",
   :realm_id => 1,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Mystra",
   :of => "Goddess of Magic",
   :alignment_id => 2,
   :image_id => '',
   :symbol => "Circle of seven stars, or nine stars encircling a flowing red mist, or a single star",
   :realm_id => 1,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Oghma",
   :of => "God of Knowledge",
   :alignment_id => 5,
   :image_id => '',
   :symbol => "Blank scroll",
   :realm_id => 1,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Savras",
   :of => "God of Divination and Fate",
   :alignment_id => 4,
   :image_id => '',
   :symbol => "Crystal ball containing many kinds of eyes",
   :realm_id => 1,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Selune",
   :of => "Goddess of the Moon",
   :alignment_id => 3,
   :image_id => '',
   :symbol => "Pair of eyes surrounded by seven stars",
   :realm_id => 1,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Shar",
   :of => "Goddess of Darkness and Loss",
   :alignment_id => 8,
   :image_id => '',
   :symbol => "Black disk encircled with a border",
   :realm_id => 1,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Silvanus",
   :of => "God of Wild Nature",
   :alignment_id => 5,
   :image_id => '',
   :symbol => "Oak leaf",
   :realm_id => 1,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Sune",
   :of => "Goddess of Love and Beauty",
   :alignment_id => 3,
   :image_id => '',
   :symbol => "Face of a beautiful red-haired woman",
   :realm_id => 1,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Talona",
   :of => "Goddess of Disease and Poison",
   :alignment_id => 9,
   :image_id => '',
   :symbol => "Three teardrops on a triangle",
   :realm_id => 1,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Talos",
   :of => "God of Storms",
   :alignment_id => 9,
   :image_id => '',
   :symbol => "Three lightning bolts radiating from a central point",
   :realm_id => 1,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Tempus",
   :of => "God of War",
   :alignment_id => 5,
   :image_id => '',
   :symbol => "Upright flaming sword",
   :realm_id => 1,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Torm",
   :of => "God of Courage and Self-sacrifice",
   :alignment_id => 1,
   :image_id => '',
   :symbol => "White right gauntlet",
   :realm_id => 1,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Tymora",
   :of => "Goddess of Good Fortune",
   :alignment_id => 3,
   :image_id => '',
   :symbol => "Face-up coin",
   :realm_id => 1,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Tyr",
   :of => "God of Justice",
   :alignment_id => 1,
   :image_id => '',
   :symbol => "Balanced scales resting on a warhammer",
   :realm_id => 1,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Umberlee",
   :of => "Goddess of the Sea",
   :alignment_id => 9,
   :image_id => '',
   :symbol => "Wave curling left and right",
   :realm_id => 1,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Waukeen",
   :of => "Goddess of Trade",
   :alignment_id => 5,
   :image_id => '',
   :symbol => "Upright coin with Waukeen's profile facing left",
   :realm_id => 1,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Beory",
   :of => "Goddess of Nature",
   :alignment_id => 5,
   :image_id => '',
   :symbol => "Green disk",
   :realm_id => 2,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Boccob",
   :of => "God of Magic",
   :alignment_id => 5,
   :image_id => '',
   :symbol => "Eye within a pentagram",
   :realm_id => 2,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Celestian",
   :of => "God of Stars and Wanderers",
   :alignment_id => 5,
   :image_id => '',
   :symbol => "Arc of seven stars inside a circle",
   :realm_id => 2,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Ehlonna",
   :of => "Goddess of Woodlands",
   :alignment_id => 2,
   :image_id => '',
   :symbol => "Unicorn horn",
   :realm_id => 2,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Erythnul",
   :of => "God of Envy and Slaughter",
   :alignment_id => 9,
   :image_id => '',
   :symbol => "Blood drop",
   :realm_id => 2,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Fharlanghn",
   :of => "God of Horizons and Travel",
   :alignment_id => 2,
   :image_id => '',
   :symbol => "Circle cross by a curved horizon line",
   :realm_id => 2,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Heironeuous",
   :of => "God of Chivalry and Valor",
   :alignment_id => 1,
   :image_id => '',
   :symbol => "Lightning bolt",
   :realm_id => 2,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Hextor",
   :of => "God of War and Discord",
   :alignment_id => 7,
   :image_id => '',
   :symbol => "Six arrows facing downward in a fan",
   :realm_id => 2,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Kord",
   :of => "God of Athletics and Sport",
   :alignment_id => 3,
   :image_id => '',
   :symbol => "Four spears and four maces radiating out from a central point",
   :realm_id => 2,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Incabulos",
   :of => "God of Plague and Famine",
   :alignment_id => 8,
   :image_id => '',
   :symbol => "Reptilian eye with a horizontal diamond",
   :realm_id => 2,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Istus",
   :of => "Goddess of Fate and Destiny",
   :alignment_id => 5,
   :image_id => '',
   :symbol => "Weaver's spindle with three strands",
   :realm_id => 2,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Iuz",
   :of => "God of Pain and Oppression",
   :alignment_id => 9,
   :image_id => '',
   :symbol => "Grinning human skull",
   :realm_id => 2,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Nerull",
   :of => "God of Death",
   :alignment_id => 8,
   :image_id => '',
   :symbol => "Skull with either a sickle or a scythe",
   :realm_id => 2,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Obad-Hai",
   :of => "God of Nature",
   :alignment_id => 5,
   :image_id => '',
   :symbol => "Oak leaf and acorn",
   :realm_id => 2,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Olidammara",
   :of => "God of Revelry",
   :alignment_id => 6,
   :image_id => '',
   :symbol => "Laughing mask",
   :realm_id => 2,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Pelor",
   :of => "God of the Sun and Healing",
   :alignment_id => 2,
   :image_id => '',
   :symbol => "Sun",
   :realm_id => 2,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Pholtus",
   :of => "God of Life and Law",
   :alignment_id => 1,
   :image_id => '',
   :symbol => "Silver sun or full moon partially eclipsed by a smaller crescent moon",
   :realm_id => 2,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Ralishaz",
   :of => "God of Ill Luck and Insanity",
   :alignment_id => 6,
   :image_id => '',
   :symbol => "Three bone fate-casting sticks",
   :realm_id => 2,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Rao",
   :of => "God of Peace and Reason",
   :alignment_id => 1,
   :image_id => '',
   :symbol => "White heart",
   :realm_id => 2,
   :is_public => true,
   :user_id => 1
  },
  {:name => "St. Cuthbert",
   :of => "God of Common Sense and Zeal",
   :alignment_id => 4,
   :image_id => '',
   :symbol => "Circle at the center of a starburst of lines",
   :realm_id => 2,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Tharizdun",
   :of => "God of Eternal Darkness",
   :alignment_id => 9,
   :image_id => '',
   :symbol => "Dark spiral or inverted ziggurat",
   :realm_id => 2,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Trithereon",
   :of => "God of Liberty and Retribution",
   :alignment_id => 3,
   :image_id => '',
   :symbol => "Triskelion",
   :realm_id => 2,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Ulaa",
   :of => "Goddess of Hills and Mountains",
   :alignment_id => 1,
   :image_id => '',
   :symbol => "Mountain with a circle at its heart",
   :realm_id => 2,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Vecna",
   :of => "God of Evil Secrets",
   :alignment_id => 8,
   :image_id => '',
   :symbol => "Hand with eye in the palm",
   :realm_id => 2,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Wee Jas",
   :of => "Goddess of Magic and Death",
   :alignment_id => 4,
   :image_id => '',
   :symbol => "Red skull in front of fireball",
   :realm_id => 2,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Paladine",
   :of => "God of Rulers and Guardians",
   :alignment_id => 1,
   :image_id => '',
   :symbol => "Silver triangle",
   :realm_id => 3,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Branchala",
   :of => "God of Music",
   :alignment_id => 2,
   :image_id => '',
   :symbol => "Bard's harp",
   :realm_id => 3,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Habbakuk",
   :of => "God of Animal Life and the Sea",
   :alignment_id => 2,
   :image_id => '',
   :symbol => "Blue bird",
   :realm_id => 3,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Kiri-Jolith",
   :of => "God of Honor and War",
   :alignment_id => 1,
   :image_id => '',
   :symbol => "Bison's horns",
   :realm_id => 3,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Majere",
   :of => "God of Meditation and Order",
   :alignment_id => 1,
   :image_id => '',
   :symbol => "Copper spider",
   :realm_id => 3,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Mishakal",
   :of => "Goddess of Healing",
   :alignment_id => 1,
   :image_id => '',
   :symbol => "Blue infinity sign",
   :realm_id => 3,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Solinari",
   :of => "God of Good Magic",
   :alignment_id => 1,
   :image_id => '',
   :symbol => "White circle or sphere",
   :realm_id => 3,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Gilean",
   :of => "God of Knowledge",
   :alignment_id => 5,
   :image_id => '',
   :symbol => "Open book",
   :realm_id => 3,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Chislev",
   :of => "Goddess of Nature",
   :alignment_id => 5,
   :image_id => '',
   :symbol => "Feather",
   :realm_id => 3,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Reorx",
   :of => "God of Craft",
   :alignment_id => 5,
   :image_id => '',
   :symbol => "Forging hammer",
   :realm_id => 3,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Shinare",
   :of => "Goddess of Wealth and Trade",
   :alignment_id => 5,
   :image_id => '',
   :symbol => "Griffon's wing",
   :realm_id => 3,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Stirrion",
   :of => "God of Fire and Change",
   :alignment_id => 5,
   :image_id => '',
   :symbol => "Mulit-colored fire",
   :realm_id => 3,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Zivilyn",
   :of => "God of Wisdom",
   :alignment_id => 5,
   :image_id => '',
   :symbol => "Great green or gold tree",
   :realm_id => 3,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Lunitari",
   :of => "Goddess of Neutral Magic",
   :alignment_id => 5,
   :image_id => '',
   :symbol => "Red circle or sphere",
   :realm_id => 3,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Takhisis",
   :of => "Goddess of Night and Hatred",
   :alignment_id => 7,
   :image_id => '',
   :symbol => "Black crescent",
   :realm_id => 3,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Chemosh",
   :of => "God of the Undead",
   :alignment_id => 7,
   :image_id => '',
   :symbol => "Yellow skull",
   :realm_id => 3,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Hiddukel",
   :of => "God of Lies and Greed",
   :alignment_id => 9,
   :image_id => '',
   :symbol => "Broken merchant's scales",
   :realm_id => 3,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Morgion",
   :of => "God of Disease and Secrecy",
   :alignment_id => 8,
   :image_id => '',
   :symbol => "Hood with two red eyes",
   :realm_id => 3,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Sargonnas",
   :of => "God of Vengeance and Fire",
   :alignment_id => 7,
   :image_id => '',
   :symbol => "Stylized red condor",
   :realm_id => 3,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Zeboim",
   :of => "Goddess of the Sea and Storms",
   :alignment_id => 9,
   :image_id => '',
   :symbol => "Turtle shell",
   :realm_id => 3,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Nuitari",
   :of => "God of Evil Magic",
   :alignment_id => 7,
   :image_id => '',
   :symbol => "Black circle or sphere",
   :realm_id => 3,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Arawai",
   :of => "Goddess of Fertility",
   :alignment_id => 2,
   :image_id => '',
   :symbol => "Sheaf of wheat tied with green ribbon",
   :realm_id => 4,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Aureon",
   :of => "God of Law and Knowledge",
   :alignment_id => 4,
   :image_id => '',
   :symbol => "Open tome",
   :realm_id => 4,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Balinor",
   :of => "God of Beasts and the Hunt",
   :alignment_id => 5,
   :image_id => '',
   :symbol => "Pair of antlers",
   :realm_id => 4,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Boldrei",
   :of => "Goddess of Community and Home",
   :alignment_id => 1,
   :image_id => '',
   :symbol => "Fire in a stone hearth",
   :realm_id => 4,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Dol Arrah",
   :of => "Goddess of Sunlight and Honor",
   :alignment_id => 1,
   :image_id => '',
   :symbol => "Rising sun",
   :realm_id => 4,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Dol Dorn",
   :of => "God of Strength at Arms",
   :alignment_id => 3,
   :image_id => '',
   :symbol => "Longsword crossed over a shield",
   :realm_id => 4,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Kol Korran",
   :of => "God of Trade and Wealth",
   :alignment_id => 5,
   :image_id => '',
   :symbol => "Nine-sided gold coin",
   :realm_id => 4,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Olladra",
   :of => "Goddess of Good Fortune",
   :alignment_id => 2,
   :image_id => '',
   :symbol => "Domino",
   :realm_id => 4,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Onatar",
   :of => "Goddess of Good Fortune",
   :alignment_id => 2,
   :image_id => '',
   :symbol => "Corssed hammer and tongs",
   :realm_id => 4,
   :is_public => true,
   :user_id => 1
  },
  {:name => "The Devourer",
   :of => "God of Nature's Wrath",
   :alignment_id => 8,
   :image_id => '',
   :symbol => "Bundle of five sharpened bones",
   :realm_id => 4,
   :is_public => true,
   :user_id => 1
  },
  {:name => "The Fury",
   :of => "Goddess of Wrath and Madness",
   :alignment_id => 8,
   :image_id => '',
   :symbol => "Winged wyrm with woman's head and upper body",
   :realm_id => 4,
   :is_public => true,
   :user_id => 1
  },
  {:name => "The Keeper",
   :of => "God of Greed and Death",
   :alignment_id => 8,
   :image_id => '',
   :symbol => "Dragonshard stone in the shape of a fang",
   :realm_id => 4,
   :is_public => true,
   :user_id => 1
  },
  {:name => "The Mockery",
   :of => "God of Violence and Treachery",
   :alignment_id => 8,
   :image_id => '',
   :symbol => "Five blood-spattered tools",
   :realm_id => 4,
   :is_public => true,
   :user_id => 1
  },
  {:name => "The Shadow",
   :of => "God of Dark Magic",
   :alignment_id => 9,
   :image_id => '',
   :symbol => "Obsidian tower",
   :realm_id => 4,
   :is_public => true,
   :user_id => 1
  },
  {:name => "The Traveler",
   :of => "Deity of Chaos and Change",
   :alignment_id => 6,
   :image_id => '',
   :symbol => "Four crossed, rune-inscribed bones",
   :realm_id => 4,
   :is_public => true,
   :user_id => 1
  },
  {:name => "The Silver Flame",
   :of => "Deity of Protection and Good",
   :alignment_id => 1,
   :image_id => '',
   :symbol => "Flame drawn on silver or molded from silver",
   :realm_id => 4,
   :is_public => true,
   :user_id => 1
  },
  {:name => "The Blood of Vol",
   :of => "Philosophy of Immortality and Undeath",
   :alignment_id => 4,
   :image_id => '',
   :symbol => "Stylized dragon skull on red teardrop gem",
   :realm_id => 4,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Cults of the Dragon Below",
   :of => "Deities of Madness",
   :alignment_id => 8,
   :image_id => '',
   :symbol => "Varies",
   :realm_id => 4,
   :is_public => true,
   :user_id => 1
  },
  {:name => "The Path of Light",
   :of => "Philosophy of Light and Self-improvement",
   :alignment_id => 4,
   :image_id => '',
   :symbol => "Brilliant crystal",
   :realm_id => 4,
   :is_public => true,
   :user_id => 1
  },
  {:name => "The Undying Court",
   :of => "Elven Ancestors",
   :alignment_id => 2,
   :image_id => '',
   :symbol => "Varies",
   :realm_id => 4,
   :is_public => true,
   :user_id => 1
  },
  {:name => "The Spirits of the Past",
   :of => "Elven Ancestors",
   :alignment_id => 3,
   :image_id => '',
   :symbol => "Varies",
   :realm_id => 4,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Bahamut",
   :of => "Dragon God of Good",
   :alignment_id => 1,
   :image_id => '',
   :symbol => "Dragon's head in profile",
   :realm_id => 5,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Bilbdoolpoolp",
   :of => "Kuo-toa Goddess",
   :alignment_id => 8,
   :image_id => '',
   :symbol => "Lobster head or black pearl",
   :realm_id => 5,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Corellon Larethian",
   :of => "Elf Deity of Art and Magic",
   :alignment_id => 3,
   :image_id => '',
   :symbol => "Quarter moon or starburst",
   :realm_id => 5,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Deep Sashelas",
   :of => "Elf God of the Sea",
   :alignment_id => 3,
   :image_id => '',
   :symbol => "Dolphin",
   :realm_id => 5,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Eadro",
   :of => "Merfolk Deity of the Sea",
   :alignment_id => 5,
   :image_id => '',
   :symbol => "Spiral design",
   :realm_id => 5,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Garl Glittergold",
   :of => "Gnome God of Trickery and Wiles",
   :alignment_id => 1,
   :image_id => '',
   :symbol => "Gold nugget",
   :realm_id => 5,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Grolantor",
   :of => "Hill Giant God of War",
   :alignment_id => 9,
   :image_id => '',
   :symbol => "Wooden club",
   :realm_id => 5,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Gruumsh",
   :of => "Orc God of Storms and War",
   :alignment_id => 9,
   :image_id => '',
   :symbol => "Unblinking eye",
   :realm_id => 5,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Hruggek",
   :of => "Bugbear God of Violence",
   :alignment_id => 9,
   :image_id => '',
   :symbol => "Morningstar",
   :realm_id => 5,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Kurtulmak",
   :of => "Kobold God of War and Mining",
   :alignment_id => 7,
   :image_id => '',
   :symbol => "Gnome skull",
   :realm_id => 5,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Laogzed",
   :of => "Troglodyte God of Hunger",
   :alignment_id => 9,
   :image_id => '',
   :symbol => "Image of the lizard/toad god",
   :realm_id => 5,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Lolth",
   :of => "Drow Goddess of Spiders",
   :alignment_id => 9,
   :image_id => '',
   :symbol => "Spider",
   :realm_id => 5,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Maglubiyet",
   :of => "Goblinoid God of War",
   :alignment_id => 7,
   :image_id => '',
   :symbol => "Bloody axe",
   :realm_id => 5,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Moradin",
   :of => "Dwarf God of Creation",
   :alignment_id => 1,
   :image_id => '',
   :symbol => "Hammer and anvil",
   :realm_id => 5,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Rillifane Rallathil",
   :of => "Wood Elf God of Nature",
   :alignment_id => 3,
   :image_id => '',
   :symbol => "Oak",
   :realm_id => 5,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Sehanine Moonbow",
   :of => "Elf Goddess of the Moon",
   :alignment_id => 3,
   :image_id => '',
   :symbol => "Crescent moon",
   :realm_id => 5,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Sekolah",
   :of => "Sahuagin God of the Hunt",
   :alignment_id => 7,
   :image_id => '',
   :symbol => "Shark",
   :realm_id => 5,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Semuanya",
   :of => "Lizardfolk Deity of Survival",
   :alignment_id => 5,
   :image_id => '',
   :symbol => "Egg",
   :realm_id => 5,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Skerrit",
   :of => "Centaur and Satyr God of Nature",
   :alignment_id => 5,
   :image_id => '',
   :symbol => "Oak growing from acorn",
   :realm_id => 5,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Skoraeus Stonebones",
   :of => "God of Stone Giants and Art",
   :alignment_id => 5,
   :image_id => '',
   :symbol => "Stalactite",
   :realm_id => 5,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Surtur",
   :of => "God of Fire Giants and Craft",
   :alignment_id => 7,
   :image_id => '',
   :symbol => "Flaming sword",
   :realm_id => 5,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Thrym",
   :of => "God of Frost Giants and Strength",
   :alignment_id => 9,
   :image_id => '',
   :symbol => "White double-bladed axe",
   :realm_id => 5,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Tiamat",
   :of => "Dragon Goddess of Evil",
   :alignment_id => 7,
   :image_id => '',
   :symbol => "Dragon head with five claw marks",
   :realm_id => 5,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Yondalla",
   :of => "Halfling Goddess of Fertility and Protection",
   :alignment_id => 1,
   :image_id => '',
   :symbol => "Shield",
   :realm_id => 5,
   :is_public => true,
   :user_id => 1
  },
  {:name => "The Daghdha",
   :of => "God of Weather and Crops",
   :alignment_id => 3,
   :image_id => '',
   :symbol => "Bubbling cauldron or shield",
   :realm_id => 6,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Arawn",
   :of => "God of Life and Death",
   :alignment_id => 8,
   :image_id => '',
   :symbol => "Black star on gray background",
   :realm_id => 6,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Belenus",
   :of => "God of Sun, Light, and Warmth",
   :alignment_id => 2,
   :image_id => '',
   :symbol => "Solar disk and standing stones",
   :realm_id => 6,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Brigantia",
   :of => "Goddess of Rivers and Livestock",
   :alignment_id => 2,
   :image_id => '',
   :symbol => "Footbridge",
   :realm_id => 6,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Diancecht",
   :of => "God of Medicine and Healing",
   :alignment_id => 1,
   :image_id => '',
   :symbol => "Crossed oak and mistletoe branch",
   :realm_id => 6,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Dunatis",
   :of => "God of Mountains and Peaks",
   :alignment_id => 5,
   :image_id => '',
   :symbol => "Red sun-capped mountain peak",
   :realm_id => 6,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Goibhniu",
   :of => "God of Smiths and Healing",
   :alignment_id => 2,
   :image_id => '',
   :symbol => "Giant mallet over sword",
   :realm_id => 6,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Lugh",
   :of => "God of Arts, Travel, and Commerce",
   :alignment_id => 6,
   :image_id => '',
   :symbol => "Pair of long hands",
   :realm_id => 6,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Manannan mac Lir",
   :of => "God of Oceans and Sea Creatures",
   :alignment_id => 4,
   :image_id => '',
   :symbol => "Wave of white water on green",
   :realm_id => 6,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Math Mathonwy",
   :of => "God of Magic",
   :alignment_id => 8,
   :image_id => '',
   :symbol => "Staff",
   :realm_id => 6,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Morrigan",
   :of => "Goddess of Battle",
   :alignment_id => 9,
   :image_id => '',
   :symbol => "Two crossed spears",
   :realm_id => 6,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Nuada",
   :of => "God of War and Warriors",
   :alignment_id => 5,
   :image_id => '',
   :symbol => "Silver hand on black background",
   :realm_id => 6,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Oghma",
   :of => "God of Speech and Writing",
   :alignment_id => 2,
   :image_id => '',
   :symbol => "Unfurled scroll",
   :realm_id => 6,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Silvanus",
   :of => "God of Nature and Forests",
   :alignment_id => 5,
   :image_id => '',
   :symbol => "Summer oak tree",
   :realm_id => 6,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Zeus",
   :of => "God of the Sky, Ruler of the Gods",
   :alignment_id => 5,
   :image_id => '',
   :symbol => "Fist full of lightning bolts",
   :realm_id => 7,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Aphrodite",
   :of => "Goddess of Love and Beauty",
   :alignment_id => 3,
   :image_id => '',
   :symbol => "Sea shell",
   :realm_id => 7,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Apollo",
   :of => "God of Light, Music, and Healing",
   :alignment_id => 3,
   :image_id => '',
   :symbol => "Lyre",
   :realm_id => 7,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Ares",
   :of => "God of War and Strife",
   :alignment_id => 9,
   :image_id => '',
   :symbol => "Spear",
   :realm_id => 7,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Artemis",
   :of => "Goddess of Hunting and Childbirth",
   :alignment_id => 2,
   :image_id => '',
   :symbol => "Bow and arrow on lunar disk",
   :realm_id => 7,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Athena",
   :of => "Goddess of Wisdom and Civilization",
   :alignment_id => 1,
   :image_id => '',
   :symbol => "Owl",
   :realm_id => 7,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Demeter",
   :of => "Goddess of Agriculture",
   :alignment_id => 2,
   :image_id => '',
   :symbol => "Mare's head",
   :realm_id => 7,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Dionysus",
   :of => "God of Mirth and Wine",
   :alignment_id => 6,
   :image_id => '',
   :symbol => "Thyrsus (staff tipped with pine cone)",
   :realm_id => 7,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Hades",
   :of => "God of the Underworld",
   :alignment_id => 7,
   :image_id => '',
   :symbol => "Black ram",
   :realm_id => 7,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Hecate",
   :of => "Goddess of Magic and the Moon",
   :alignment_id => 9,
   :image_id => '',
   :symbol => "Setting moon",
   :realm_id => 7,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Hephaestus",
   :of => "God of Smithing and Craft",
   :alignment_id => 2,
   :image_id => '',
   :symbol => "Hammer and anvil",
   :realm_id => 7,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Hera",
   :of => "Goddess of Marriage and Intrigue",
   :alignment_id => 6,
   :image_id => '',
   :symbol => "Fan of peacock feathers",
   :realm_id => 7,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Hercules",
   :of => "God of Strength and Adventure",
   :alignment_id => 3,
   :image_id => '',
   :symbol => "Lion's head",
   :realm_id => 7,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Hermes",
   :of => "God of Travel and Commerce",
   :alignment_id => 3,
   :image_id => '',
   :symbol => "Caduceus (winged staff and serpents)",
   :realm_id => 7,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Hestia",
   :of => "Goddess of Home and Family",
   :alignment_id => 2,
   :image_id => '',
   :symbol => "Hearth",
   :realm_id => 7,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Nike",
   :of => "Goddess of Victory",
   :alignment_id => 4,
   :image_id => '',
   :symbol => "Winged woman",
   :realm_id => 7,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Pan",
   :of => "God of Nature",
   :alignment_id => 6,
   :image_id => '',
   :symbol => "Syrinx (pan pipes)",
   :realm_id => 7,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Poseidon",
   :of => "God of the Sea and Earthquakes",
   :alignment_id => 6,
   :image_id => '',
   :symbol => "Trident",
   :realm_id => 7,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Tyche",
   :of => "Goddess of Good Fortune",
   :alignment_id => 5,
   :image_id => '',
   :symbol => "Red pentagram",
   :realm_id => 7,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Re-Horakhty",
   :of => "God of the Sun, Ruler of the Gods",
   :alignment_id => 1,
   :image_id => '',
   :symbol => "Solar disk encircled by serpent",
   :realm_id => 8,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Anubis",
   :of => "God of Judgment and Death",
   :alignment_id => 4,
   :image_id => '',
   :symbol => "Black jackal",
   :realm_id => 8,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Apep",
   :of => "God of Evil, Fire, and Serpents",
   :alignment_id => 8,
   :image_id => '',
   :symbol => "Flaming snake",
   :realm_id => 8,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Bast",
   :of => "Goddess of Cats and Vengeance",
   :alignment_id => 3,
   :image_id => '',
   :symbol => "Cat",
   :realm_id => 8,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Bes",
   :of => "God of Luck and Music",
   :alignment_id => 6,
   :image_id => '',
   :symbol => "Image of the misshapen deity",
   :realm_id => 8,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Hathor",
   :of => "Goddess of Love, Music, and Motherhood",
   :alignment_id => 2,
   :image_id => '',
   :symbol => "Horned cow's head with lunar disk",
   :realm_id => 8,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Imhotop",
   :of => "God of Crafts and Medicine",
   :alignment_id => 2,
   :image_id => '',
   :symbol => "Step pyramid",
   :realm_id => 8,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Isis",
   :of => "Goddess of Fertility and Magic",
   :alignment_id => 2,
   :image_id => '',
   :symbol => "Ankh and star",
   :realm_id => 8,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Nephthys",
   :of => "Goddess of Death and Grief",
   :alignment_id => 3,
   :image_id => '',
   :symbol => "Horns around a lunar disk",
   :realm_id => 8,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Osiris",
   :of => "God of Nature and the Underworld",
   :alignment_id => 1,
   :image_id => '',
   :symbol => "Crook and flail",
   :realm_id => 8,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Ptah",
   :of => "God of Crafts, Knowledge, and Secrets",
   :alignment_id => 4,
   :image_id => '',
   :symbol => "Bull",
   :realm_id => 8,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Set",
   :of => "God of Darkness and Desert Storms",
   :alignment_id => 9,
   :image_id => '',
   :symbol => "Coiled cobra",
   :realm_id => 8,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Sobek",
   :of => "God of Water and Crocodiles",
   :alignment_id => 7,
   :image_id => '',
   :symbol => "Crocodile head with horns and plumes",
   :realm_id => 8,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Thoth",
   :of => "God of Knowledge and Wisdom",
   :alignment_id => 5,
   :image_id => '',
   :symbol => "Ibis",
   :realm_id => 8,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Odin",
   :of => "God of Knowledge and War",
   :alignment_id => 2,
   :image_id => '',
   :symbol => "Watching blue eyes",
   :realm_id => 9,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Aegir",
   :of => "God of the Sea and Storms",
   :alignment_id => 8,
   :image_id => '',
   :symbol => "Rough ocean waves",
   :realm_id => 9,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Balder",
   :of => "God of Beauty and Poetry",
   :alignment_id => 2,
   :image_id => '',
   :symbol => "Gem-encrusted silver chalice",
   :realm_id => 9,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Forseti",
   :of => "God of Justice and Law",
   :alignment_id => 5,
   :image_id => '',
   :symbol => "Head of a bearded man",
   :realm_id => 9,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Frey",
   :of => "God of Fertility and the Sun",
   :alignment_id => 2,
   :image_id => '',
   :symbol => "Ice-blue greatsword",
   :realm_id => 9,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Freya",
   :of => "Goddess of Fertility and Love",
   :alignment_id => 2,
   :image_id => '',
   :symbol => "Falcon",
   :realm_id => 9,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Frigga",
   :of => "Goddess of Birth and Fertility",
   :alignment_id => 5,
   :image_id => '',
   :symbol => "Cat",
   :realm_id => 9,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Heimdall",
   :of => "God of Watchfulness and Loyalty",
   :alignment_id => 1,
   :image_id => '',
   :symbol => "Curling musical horn",
   :realm_id => 9,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Hel",
   :of => "Goddess of the Underworld",
   :alignment_id => 8,
   :image_id => '',
   :symbol => "Woman's face, rotting on one side",
   :realm_id => 9,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Hermod",
   :of => "God of Luck",
   :alignment_id => 6,
   :image_id => '',
   :symbol => "Winged scroll",
   :realm_id => 9,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Loki",
   :of => "God of Thieves and Trickery",
   :alignment_id => 9,
   :image_id => '',
   :symbol => "Flame",
   :realm_id => 9,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Njord",
   :of => "God of Sea and Wind",
   :alignment_id => 2,
   :image_id => '',
   :symbol => "Gold coin",
   :realm_id => 9,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Odur",
   :of => "God of Light and the Sun",
   :alignment_id => 3,
   :image_id => '',
   :symbol => "Solar disk",
   :realm_id => 9,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Sif",
   :of => "Goddess of War",
   :alignment_id => 3,
   :image_id => '',
   :symbol => "Upraised sword",
   :realm_id => 9,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Skadi",
   :of => "God of Earth and Mountains",
   :alignment_id => 5,
   :image_id => '',
   :symbol => "Mountain peak",
   :realm_id => 9,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Surtur",
   :of => "God of Fire Giants and War",
   :alignment_id => 7,
   :image_id => '',
   :symbol => "Flaming sword",
   :realm_id => 9,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Thor",
   :of => "God of Storms and Thunder",
   :alignment_id => 3,
   :image_id => '',
   :symbol => "Hammer",
   :realm_id => 9,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Thrym",
   :of => "God of Fire Giants and Cold",
   :alignment_id => 9,
   :image_id => '',
   :symbol => "White double-bladed axe",
   :realm_id => 9,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Tyr",
   :of => "God of Courage and Strategy",
   :alignment_id => 4,
   :image_id => '',
   :symbol => "Sword",
   :realm_id => 9,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Uller",
   :of => "God of Hunting and Winter",
   :alignment_id => 6,
   :image_id => '',
   :symbol => "Longbow",
   :realm_id => 9,
   :is_public => true,
   :user_id => 1
  }
])
