Tool.create([
  {:name => "Artisan's tools",
   :description => "These special tools include the items needed to pursue a craft or trade. Proficiency with a set of artisan's tools lets you add your proficiency bonus to any ability checks you make using the tools in your craft. Each type of artisan's tools requires a separate proficiency.",
   :subtype => "",
   :weight => '',
   :cost => '',
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Alchemist's supplies",
   :description => "",
   :subtype => "Artisan's tools",
   :weight => 8,
   :cost => 30,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Brewer's supplies",
   :description => "",
   :subtype => "Artisan's tools",
   :weight => 9,
   :cost => 20,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Calligrapher's supplies",
   :description => "",
   :subtype => "Artisan's tools",
   :weight => 5,
   :cost => 10,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Carpenter tools",
   :description => "",
   :subtype => "Artisan's tools",
   :weight => 6,
   :cost => 8,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Cartographer's tools",
   :description => "Artisan's tools",
   :subtype => "",
   :weight => 6,
   :cost => 15,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Cobbler's tools",
   :description => "",
   :subtype => "Artisan's tools",
   :weight => 5,
   :cost => 5,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Cook's utensils",
   :description => "",
   :subtype => "Artisan's tools",
   :weight => 8,
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Glassblower's tools",
   :description => "",
   :subtype => "Artisan's tools",
   :weight => 5,
   :cost => 30,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Jeweler's tools",
   :description => "",
   :subtype => "Artisan's tools",
   :weight => 2,
   :cost => 25,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Leatherworker's tools",
   :description => "",
   :subtype => "Artisan's tools",
   :weight => 5,
   :cost => 5,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Mason's tools",
   :description => "",
   :subtype => "Artisan's tools",
   :weight => 8,
   :cost => 10,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Painter's supplies",
   :description => "",
   :subtype => "Artisan's tools",
   :weight => 5,
   :cost => 10,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Potter's tools",
   :description => "",
   :subtype => "Artisan's tools",
   :weight => 3,
   :cost => 10,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Smith's tools",
   :description => "",
   :subtype => "Artisan's tools",
   :weight => 8,
   :cost => 20,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Tinker's tools",
   :description => "",
   :subtype => "Artisan's tools",
   :weight => 10,
   :cost => 50,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Weaver's tools",
   :description => "",
   :subtype => "Artisan's tools",
   :weight => 5,
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Woodcarver's tools",
   :description => "",
   :subtype => "Artisan's tools",
   :weight => 5,
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Disguise kit",
   :description => "This pouch of cosmetics, hair dye, and small props lets you create disguises that change your physical appearance. Proficiency with this kit lets you add your proficiency bonus to any ability checks you make to create a visual disguise.",
   :subtype => "",
   :weight => 2,
   :cost => 15,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Forgery kit",
   :description => "This small box contains a variety of papers and parchments, pens and inks, seals and sealing wax, gold and silver leaf, and other supplies necessary to create convincing forgeries of physical documents. Proficiency with this kit lets you add your proficiency bonus to any ability checks you make to create a physical forgery of a document.",
   :subtype => "",
   :weight => 5,
   :cost => 15,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Gaming set",
   :description => "This item encompasses a wide range of game pieces, including dice and decks of cards (for games such as Three-Dragon Ante). A few common examples appear on the Tools table, but other kinds of gaming sets exist. If you are proficient with a gaming set, you can add your proficiency bonus to ability checks you make to play a game with that set. Each type of gaming set requires a separate proficiency.",
   :subtype => "",
   :weight => '',
   :cost => '',
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Dice set",
   :description => "",
   :subtype => "Gaming set",
   :weight => 0,
   :cost => 1,
   :currency => "sp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Dragonchess set",
   :description => "",
   :subtype => "Gaming set",
   :weight => 0.5,
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Playing card set",
   :description => "",
   :subtype => "Gaming set",
   :weight => 0,
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Three-Dragon Ante set",
   :description => "",
   :subtype => "Gaming set",
   :weight => 0,
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Herbalism kit",
   :description => "This kit contains a variety of instruments such as clippers, mortar and pestle, and pouches and vials used by herbalists to create remedies and potions. Proficiency with this kit lets you add your proficiency bonus to any ability checks you make to identify or apply herbs. Also, proficiency with this kit is required to create antitoxin and potions or healing.",
   :subtype => "",
   :weight => 3,
   :cost => 5,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Musical instrument",
   :description => "If you have proficiency with a given musical instrument, you can add your proficiency bonus to any ability checks you make to play music with the instrument. A bard can use a musical instrument as a spellcasting focus. Each type of musical instrument requires a separate proficiency.",
   :subtype => "",
   :weight => '',
   :cost => '',
   :currency => "",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Bagpipes",
   :description => "",
   :subtype => "Musical instrument",
   :weight => 6,
   :cost => 30,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Drums",
   :description => "",
   :subtype => "Musical instrument",
   :weight => 3,
   :cost => 6,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Dulcimer",
   :description => "",
   :subtype => "Musical instrument",
   :weight => 10,
   :cost => 25,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Flute",
   :description => "",
   :subtype => "Musical instrument",
   :weight => 1,
   :cost => 2,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Lute",
   :description => "",
   :subtype => "Musical instrument",
   :weight => 2,
   :cost => 35,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Lyre",
   :description => "",
   :subtype => "Musical instrument",
   :weight => 2,
   :cost => 30,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Horn",
   :description => "",
   :subtype => "Musical instrument",
   :weight => 2,
   :cost => 3,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Pan flute",
   :description => "",
   :subtype => "Musical instrument",
   :weight => 2,
   :cost => 12,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Shawm",
   :description => "",
   :subtype => "Musical instrument",
   :weight => 1,
   :cost => 2,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Viol",
   :description => "",
   :subtype => "Musical instrument",
   :weight => 1,
   :cost => 30,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Navigator's tools",
   :description => "This set of instruments is used for navigation at sea. Proficiency with navigator's tools lets you chart a ship's course and follow navigation charts. In addition, these tools allow you to add your proficiency bonus to any ability check you make to avoid getting lost at sea.",
   :subtype => "",
   :weight => 2,
   :cost => 25,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Poisoner's kit",
   :description => "A poisoner's kit includes the vials, chemicals, and other equipment necessary for the creation of poisons. Proficiency with this kit lets you add your proficiency bonus to any ability checks you make to craft or use poisons.",
   :subtype => "",
   :weight => 2,
   :cost => 50,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Thieves' tools",
   :description => "This set of tools includes a small file, a set of lock picks, a small mirror mounted on a metal handle, a set of narrow-bladed scissors, and a pair of pliers. Proficiency with these tools lets you add your proficiency bonus to any ability checks you make to disarm traps or open locks.",
   :subtype => "",
   :weight => 1,
   :cost => 25,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  }
])
