Language.create([
  {:name => 'Celestial',
   :description => "Described as beautiful, yet alien in nature, since it developed among beings with thought patterns very unlike those of humanity.",
   :selector => 'Celestial',
   :source_file => 'Celestial.otf',
   :file_format => 'opentype',
   :font_size => 28,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Common",
   :description => 'The common language. Pretty much English',
   :selector => "Common",
   :source_file => "Common.ttf",
   :file_format => "truetype",
   :font_size => 24,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Draconic",
   :description => "Draconic is thought to be one of the oldest languages and is often used in the study of magic. The language sounds harsh to m ost other creatures and includes num erous hard consonants and sibilants.",
   :selector => 'Draconic',
   :source_file => "Draconic.otf",
   :file_format => "opentype",
   :font_size => 28,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Dwarvish",
   :description => "Dwarvish is full of hard consonants and guttural sounds, and those characteristics spill over into whatever other language a dwarf might speak.",
   :selector => 'Dwarvish',
   :source_file => "Dwarvish.otf",
   :file_format => "opentype",
   :font_size => 28,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Elvish",
   :description => "Elvish is fluid, with subtle intonations and intricate grammar. Elven literature is rich and varied, and their songs and poem s are fam ous am ong other races. Many bards learn their language so they can add Elvish ballads to their repertoires.",
   :selector => "Elvish",
   :source_file => "Elvish.otf",
   :file_format => "opentype",
   :font_size => 10,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Gnomish",
   :description => "The Gnomish language, which uses the Dwarvish script, is renow ned for its technical treatises and its catalogs of knowledge about the natural world.",
   :selector => "Gnomish",
   :source_file => "Gnomish.ttf",
   :file_format => "truetype",
   :font_size => 28,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Goblin",
   :description => "Also known as Ghukliak, was the language spoken by goblins, hobgoblins, and bugbears. It originally used the Dethek script, but by the late 15th century, goblinoids had begun using the Thorass alphabet instead.",
   :selector => "Goblin",
   :source_file => "Goblin.otf",
   :file_format => "opentype",
   :font_size => 28,
   :is_public => true,
   :user_id => 1
  },
  {:name => "High Drowic",
   :description => "High Drow is a complex language and has a larger, runic alphabet. This language is primarily used by priestesses in their rituals and by nobles who wish not to be understood by lower-born drow and slaves",
   :selector => "Drowic",
   :source_file => "HighDrowic.otf",
   :file_format => "opentype",
   :font_size => 28,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Infernal",
   :description => "It is described as beautiful, yet alien in nature, since it developed among beings with thought patterns very unlike those of humanity.",
   :selector => "Infernal",
   :source_file => "Infernal.otf",
   :file_format => "opentype",
   :font_size => 28,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Theives Cant",
   :description => "A secret mix of dialect, jargon, and code that allows you to hide messages in seemingly normal conversation.",
   :selector => "Thieves",
   :source_file => "Thieves.ttf",
   :file_format => "truetype",
   :font_size => 24,
   :is_public => true,
   :user_id => 1
  },
  {:name => "Undercommon",
   :description => "A trade language spoken by the majority of intelligent races native to the Underdark.",
   :selector => "Undercommon",
   :source_file => "Undercommon.otf",
   :file_format => "opentype",
   :font_size => 28,
   :is_public => true,
   :user_id => 1
  }
])
