Trait.create([
  {:race_id => 1,
   :name => "Draconic Ancestry",
   :table_id => 11,
   :is_public => true,
   :user_id => 1
  },
  {:race_id => 1,
   :name => "Breath Weapon",
   :table_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:race_id => 1,
   :name => "Damage Resistance",
   :table_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:race_id => 9,
   :name => "Darkvision",
   :table_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:race_id => 9,
   :name => "Dwarven Resilience",
   :table_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:race_id => 9,
   :name => "Dwarven Combat Training",
   :table_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:race_id => 9,
   :name => "Tool Proficiency",
   :table_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:race_id => 9,
   :name => "Stonecunning",
   :table_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:race_id => 9,
   :name => "Dwarven Toughness",
   :table_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:race_id => 11,
   :name => "Darkvision",
   :table_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:race_id => 11,
   :name => "Dwarven Resilience",
   :table_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:race_id => 11,
   :name => "Dwarven Combat Training",
   :table_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:race_id => 11,
   :name => "Tool Proficiency",
   :table_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:race_id => 11,
   :name => "Stonecunning",
   :table_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:race_id => 11,
   :name => "Dwarven Armor Training",
   :table_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:race_id => 2,
   :name => "Superior Darkvision",
   :table_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:race_id => 2,
   :name => "Keen Senses",
   :table_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:race_id => 2,
   :name => "Fey Ancestry",
   :table_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:race_id => 2,
   :name => "Trance",
   :table_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:race_id => 2,
   :name => "Sunlight Sensitivity",
   :table_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:race_id => 2,
   :name => "Drow Magic",
   :table_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:race_id => 2,
   :name => "Drow Weapon Training",
   :table_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:race_id => 8,
   :name => "Superior Darkvision",
   :table_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:race_id => 8,
   :name => "Keen Senses",
   :table_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:race_id => 8,
   :name => "Fey Ancestry",
   :table_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:race_id => 8,
   :name => "Trance",
   :table_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:race_id => 8,
   :name => "Elf Weapon Training",
   :table_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:race_id => 8,
   :name => "Cantrip",
   :table_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:race_id => 8,
   :name => "Extra Language",
   :table_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:race_id => 14,
   :name => "Superior Darkvision",
   :table_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:race_id => 14,
   :name => "Keen Senses",
   :table_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:race_id => 14,
   :name => "Fey Ancestry",
   :table_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:race_id => 14,
   :name => "Trance",
   :table_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:race_id => 14,
   :name => "Elf Weapon Training",
   :table_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:race_id => 14,
   :name => "Fleet of Foot",
   :table_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:race_id => 14,
   :name => "Mask of the Wild",
   :table_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:race_id => 3,
   :name => "Darkvision",
   :table_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:race_id => 3,
   :name => "Gnome Cunning",
   :table_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:race_id => 3,
   :name => "Natural Illusionist",
   :table_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:race_id => 3,
   :name => "Speak with Small Beasts",
   :table_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:race_id => 12,
   :name => "Darkvision",
   :table_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:race_id => 12,
   :name => "Gnome Cunning",
   :table_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:race_id => 12,
   :name => "Artificer's Lore",
   :table_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:race_id => 12,
   :name => "Tinker",
   :table_id => 12,
   :is_public => true,
   :user_id => 1
  },
  {:race_id => 4,
   :name => "Darkvision",
   :table_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:race_id => 4,
   :name => "Fey Ancestry",
   :table_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:race_id => 4,
   :name => "Skill Versatility",
   :table_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:race_id => 7,
   :name => "Darkvision",
   :table_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:race_id => 7,
   :name => "Menacing",
   :table_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:race_id => 7,
   :name => "Relentless Endurance",
   :table_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:race_id => 7,
   :name => "Savage Attacks",
   :table_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:race_id => 5,
   :name => "Lucky",
   :table_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:race_id => 5,
   :name => "Brave",
   :table_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:race_id => 5,
   :name => "Halfling Nimbleness",
   :table_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:race_id => 5,
   :name => "Naturally Stealthy",
   :table_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:race_id => 6,
   :name => "Lucky",
   :table_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:race_id => 6,
   :name => "Brave",
   :table_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:race_id => 6,
   :name => "Halfling Nimbleness",
   :table_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:race_id => 6,
   :name => "Stout Resilience",
   :table_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:race_id => 13,
   :name => "Darkvision",
   :table_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:race_id => 13,
   :name => "Hellish Resistance",
   :table_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:race_id => 13,
   :name => "Infernal Legacy",
   :table_id => "",
   :is_public => true,
   :user_id => 1
  }
])
