RacialTraitDescription.create([
  {:racial_trait_id => 1,
   :description => "Dragonborn look very much like dragons standing erect in humanoid form, though they lack wings or a tail. The first dragonborn had scales of vibrant hues matching the colors of their dragon kin, but generations of interbreeding have created a more uniform appearance. Their small, fine scales are usually brass or bronze in color, sometimes ranging to scarlet, rust, gold, or copper-green. They are tall and strongly built, often standing close to 6'h feet tall and weighing 300 pounds or more.",
  },
  {:racial_trait_id => 1,
   :description => "Their hands and feet are strong, talonlike claws with three fingers and a thumb on each hand. The blood of a particular type of dragon runs very strong through some dragonborn clans. These dragonborn often boast scales that more closely match those of their dragon ancestor-bright red, green, blue, or white, lustrous black, or gleaming metallic gold, silver, brass, copper, or bronze.",
  },
  {:racial_trait_id => 2,
   :description => "To any dragonborn, the clan is more important than life itself. Dragonborn owe their devotion and respect to their clan above all e1se, even the gods. Each dragonborn's conduct reflects on the honor of his or her clan, and bringing dishonor to the clan can result in expulsion and exile. Each dragonborn knows his or her station and duties within the clan, and honor demands maintaining the bounds of that position.",
  },
  {:racial_trait_id => 2,
   :description => "A continual drive for self-improvement reflects the self-sufficiency of the race as a whole. Dragonborn value skill and excellence in all endeavors. They hate to fail, and they push themselves to extreme efforts before they give up on something. A dragonborn holds mastery of a particular skill as a lifetime goal. Members of other races who share the same commitment find it easy to earn the respect of a dragonborn.",
  },
  {:racial_trait_id => 2,
   :description => "Though all dragonborn strive to be self-sufficient, they recognize that help is sometimes needed in difficult situations. But the best source for such help is the clan, and when a clan needs help. it turns to another dragonborn clan before seeking aid from other races-or even fram the gods.",
  },
  {:racial_trait_id => 3,
   :description => "The dragonborn are uncommon. They don't exist in every world of D&D, and even where they are found. They are less widespread than dwarves, elves, halfings, and humans.",
  },
  {:racial_trait_id => 3,
   :description => "In the cosmopolitan cities of the D&D multiverse, most people hardly look twice at members of even the most exotic races. But the small towns and villages that dot the countryside are different. The common folk aren't accustomed to seeing members of these races, and they react accordingly.",
  },
  {:racial_trait_id => 3,
   :description => "Its easy to assume that a dragonborn is a monster, especially if his or her scales betray a chromatic heritage. Unless the dragonborn starts breathing fire and causing destruction though, people are likely to respond with caution rather than outright fear.",
  },
{:racial_trait_id => 4,
   :description => "In the Dragonlance setting, the followers of the evil goddess Takhisis learned a dark ritual that let them corrupt the eggs of metallic dragons, producing evil dragonborn called draconians. Five types of draconians, corresponding to the five types of metallic dragons, fought for Takhisis in the War of the Lance: auraks (gold). baaz (brass), bozak (bronze). kapak (copper), and sivak (silver). In place of their draconic breath weapons, they have unique magical abilities.",
  },
  {:racial_trait_id => 5,
   :description => "Dragonborn have personal names given at birth, but they put their clan names first as a mark of honor. A childhood name or nickname is often used among clutchmates as a descriptive term or a term of endearment. The name might recall an event or center on a habit.",
  },
  {:racial_trait_id => 6,
   :description => "With their unearthly grace and fine features, elves appear hauntingly beautiful to humans and members of many other races. They are slightly shorter than humans on average, ranging from well under 5 feet tall to just over 6 feet. They are more slender than humans, weighing only 100 to 145 pounds. Males and females are about the same height, and males are only marginally heavier than females.",
  },
  {:racial_trait_id => 6,
   :description => "Elves' coloration encompasses the normal human range and also includes skin in shades of copper, bronze, and almost bluish-white, hair of green or blue, and eyes like pools of liquid gold or silver. Elves have no facial and little body hair. They favor elegant clothing in bright colors, and they enjoy simple yet lovely jewelry,",
  },
  {:racial_trait_id => 7,
   :description => "Elves can live well over 700 years, giving them a broad perspective on events that might trouble the shorter-lived races more deeply, They are more often amused than excited, and more likely to be curious than greedy. They tend to remain aloof and unfazed by petty happenstance. When pursuing a goal, however, whether adventuring on a mission or learning a new skill or art, elves can be focused and relentless. They are slow to make friends and enemies, and even slower to forget them. They reply to petty insults with disdain and to serious insults with vengeance.",
  },
  {:racial_trait_id => 7,
   :description => "Like the branches of a young tree, elves are flexible in the face of danger. They trust in diplomacy and compromise to resolve differences before they escalate to violence. They have been known to retreat from intrusions into their woodland homes, confident that they can simply wait the invaders out. But when the need arises, elves reveal a stern martial side, demonstrating skill with sword, bow, and strategy.",
  },
  {:racial_trait_id => 8,
   :description => "Most elves dwell in small forest villages hidden among the trees. Elves hunt game, gather food, and grow vegetables, and their skill and magic allow them to support themselves without the need for clearing and plowing land. They are talented artisans, crafting finely worked clothes and art objects. Their contact with outsiders is usually limited, though a few elves make a good living by trading crafted items for metals (which they have no interest in mining).",
  },
  {:racial_trait_id => 8,
   :description => "Elves encountered outside their own lands are commonly traveling minstrels, artists, or sages. Human nobles compete for the services of elf instructors to teach swordplay or magic to their children.",
  },
  {:racial_trait_id => 9,
   :description => "Elves take up adventuring out of wanderlust. Since they are so long-lived, they can enjoy centuries of exploration and discovery. They dislike the pace of human society, which is regimented from day to day but constantly changing over decades, so they find careers that let them travel freely and set their own pace. Elves also enjoy exercising their martial prowess or gaining greater magical power, and adventuring allows them to do so. Some might join with rebels fighting against oppression, and others might become champions of moral causes.",
  },
  {:racial_trait_id => 10,
   :description => "Although they can be haughty, elves are generally gracious even to those who fall short of their high expectations- which is most non.elves. 5till, they can find good in just about anyone.",
  },
  {:racial_trait_id => 10,
   :description => 'Dwarves: "Dwarves are dull, clumsy oafs. But what they lack in humor, sophistication, and manners, they make up in valor. And I must admit, their best smiths produce art that approaches elven quality."',
  },
  {:racial_trait_id => 10,
   :description => 'Halflings: "Halflings are people of simple pleasures, and that is not a quality to scorn. They\'re good folk, they care for each other and tend their gardens, and they have proven themselves tougher than they seem when the need arises."',
  },
  {:racial_trait_id => 10,
   :description => 'Humans: "All that haste, their ambition and drive to accomplish something before their brief lives pass away-human endeavors seem 50 futile sometimes. But then you look at what they have accomplished, and you have to appreciate their achievements. If only they could slow down and learn some refinement."',
  },
  {:racial_trait_id => 11,
   :description => "Were it not for one renowned exception, the race of drow would be universally reviled. To most, they are a race of demon-worshiping marauders dwelling in the subterranean depths of the Underdark, emerging only on the blackest nights to pillage and slaughter the surface dwellers they despise. Their society is depraved and preoccupied with the favor of Lolth, their spider-goddess, who sanctions murder and the extermination of entire families as noble houses vie for position.",
  },
  {:racial_trait_id => 11,
   :description => "Yet one drow, at least, broke the mold. In the world of the Forgotten Realms, Drizzt Do'Urden, ranger of the North, has proven his quality as a good-hearted defender of the weak and innocent. Rejecting his heritage and adrift in a world that looks upon him with terror and loathing, Drizzt is a model for those few drow who follow in his footsteps, trying lo find a life apart from the evil society of their Underdark homes.",
  },
  {:racial_trait_id => 11,
   :description => "Drow grow up believing that surface-dwelling races are inferior, worthless except as slaves. Drow who develop a conscience or find it necessary to cooperate with members of other races find it hard lo overcome that prejudice, especially when they are so often on the receiving end of hatred.",
  },
  {:racial_trait_id => 12,
   :description => "Elves are considered children until they declare themselves adults, some time after the hundredth birthday, and before this period they are called by child names.",
  },
  {:racial_trait_id => 12,
   :description => "On declaring adulthood, an elf selects an adult name, although those who knew him or her as a youngster might continue to use the child name. Each elf's adult name is a unique creation, though It might reflect the names of respected individuals or other family members. Little distinction exists between male names and female names; the groupings here reflect only general tendencies. In addition, every elf bears a family name, typically a combination of other Elvish words. Some elves traveling among humans translate their family names into Common, but others retain the Elvish version.",
  },
  {:racial_trait_id => 13,
   :description => "A gnome's energy and enthusiasm for living shines through every inch of his or her tiny body. Gnomes average slightly over 3 feet tall and weigh 40 to 45 pounds. Their tan or brown faces are usually adorned with broad smiles (beneath their prodigious noses), and their bright eyes shine with excitement. Their air hair has a tendency to stick out in every direction, as if expressing the gnome's insatiable interest in everything around.",
  },
  {:racial_trait_id => 13,
   :description => "A gnome's personality is writ large in his or her appearance. A male gnome's beard, in contrast to his wild hair, is kept carefully trimmed but often styled into curious forks or neat points. A gnome's clothing, though usually made in modest earth tones, is elaborately decorated with embroidery, embossing, or gleaming jewels.",
  },
  {:racial_trait_id => 14,
   :description => "As far as gnomes are concerned, being alive is a wonderful thing, and they squeeze every ounce of enjoyment out of their three to five centuries of life. Humans might wonder about getting bored over the course of such a long life, and elves take plenty of time to savor the beauties of the world in their long years, but gnomes seem to worry that even with all that time, they can't get in enough of the things they want to do and see.",
  },
  {:racial_trait_id => 14,
   :description => "Gnomes speak as if they can't get the thoughts out of their heads fast enough. Even as they offer ideas and opinions on a range of subjects, they still manage to listen carefully to others, adding the appropriate exclamations of surprise and appreciation along the way.",
  },
  {:racial_trait_id => 14,
   :description => "Though gnomes love jokes of all kinds, particularly puns and pranks, they're just as dedicated to the more serious tasks they undertake, Many gnomes are skilled engineers, alchemists, tinkers, and inventors, They're willing to make mistakes and laugh at themselves in the process of perfecting what they do, taking bold (sometimes foolhardy) risks and dreaming large,",
  },
  {:racial_trait_id => 15,
   :description => "Gnomes make their homes in hilly, wooded lands. They live underground but get more fresh air than dwarves do, enjoying the natural, living world on the surface whenever they can, Their homes are well hidden by both clever construction and simple illusions. Welcome visitors are quickly ushered into the bright, warm burrows. Those who are not welcome are unlikely to find the burrows in the first place,",
  },
  {:racial_trait_id => 15,
   :description => "Gnomes who settle in human lands are commonly gem cutters, engineers, sages, or tinkers. Some human families retain gnome tutors, ensuring that their pupils enjoy a mix of serious learning and delighted enjoyment. A gnome might tutor several generations of a single human family over the course of his or her long life.",
  },
  {:racial_trait_id => 16,
   :description => "Curious and impulsive, gnomes might take up adventuring as a way to see the world or for the love of exploring. As lovers of gems and other fine items, some gnomes take to adventuring as a quick, if dangerous, path to wealth. Regardless of what spurs them lo adventure, gnomes who adopt this way of life eke as much enjoyment out of it as they do out of any other activity they undertake, sometimes to the great annoyance of their adventuring companions.",
  },
  {:racial_trait_id => 17,
   :description => "A third subrace of gnomes, the deep gnomes (or svirfneblin), live in small communities scattered in the Underdark. Unlike the duergar and the drow, svirfneblin are as good as their surface cousins. However, their humor and enthusiasm are dampened by their oppressive environment, and their inventive expertise is directed mostly toward stonework.",
  },
  {:racial_trait_id => 18,
   :description => "It's rare for a gnome to be hostile or malicious unless he or she has suffered a grievous injury. Gnomes know that most races don't share their sense of humor, but they enjoy anyone's company just as they enjoy everything else they set out to do.",
  },
  {:racial_trait_id => 19,
   :description => "The gnome are uncommon. They don't exist in every world of D&D, and even where they are found. They are less widespread than dwarves, elves, halfings, and humans.",
  },
  {:racial_trait_id => 19,
   :description => "In the cosmopolitan cities of the D&D multiverse, most people hardly look twice at members of even the most exotic races. But the small towns and villages that dot the countryside are different. The common folk aren't accustomed to seeing members of these races, and they react accordingly.",
  },
  {:racial_trait_id => 19,
   :description => "Gnomes don't look like a threat and can quickly disarm suspicion with good humor. The common folk are often curious about gnomes, likely never having seen one before, but they are rarely hostile or fearful.",
  },
  {:racial_trait_id => 20,
   :description => "Gnomes love names, and most have half a dozen or so. A gnome's mother, father, clan elder, aunts, and uncles each give the gnome a name, and various nicknames from just about everyone else might or might not stick over time. Gnome names are typically variants on the names of ancestors or distant relatives, though some are purely new inventions. When dealing with humans and others who are 'stuffy' about names, a gnome learns to use no more than three names: a personal name, a clan name, and a nickname, choosing the one in each category that's the most fun to say.",
  },
  {:racial_trait_id => 21,
   :description => "To humans, half-elves look like elves, and to elves, they look human. In height, they're on par with both parents, though they're neither as slender as elves nor as broad as humans. They range from under 5 feet to about 6 feet tall, and from 100 to 180 pounds, with men only slightly taller and heavier than women. Half-elf men do have facial hair, and sometimes grow beards to mask their elven ancestry. Half-elven coloration and features lie somewhere between their human and elf parents, and thus show a variety even more pronounced than that found among either race. They tend to have the eyes of their elven parents.",
  },
  {:racial_trait_id => 22,
   :description => "Half-elves have no lands of their own, though they are welcome in human cities and somewhat less welcome in elven forests. In large cities in regions where elves and humans interact often, half-elves are sometimes numerous enough to form small communities of their own. They enjoy the company of other half-elves, the only people who truly understand what it is to live between these two worlds.",
  },
  {:racial_trait_id => 22,
   :description => "In most parts of the world, though, half-elves are uncommon enough that one might live for years without meeting another. Some half-elves prefer to avoid company altogether, wandering the wilds as trappers, foresters, hunters, or adventurers and visiting civilization only rarely. Like elves, they are driven by the wanderlust that comes of their longevity. Others, in contrast, throw themselves into the thick of society, putting their charisma and social skills to great use in diplomatic roles or as swindlers.",
  },
  {:racial_trait_id => 23,
   :description => "Many half-elves learn at an early age to get along with everyone, defusing hostility and finding common ground. As a race, they have elven grace without elven aloofness and human energy without human boorishness. They often make excellent ambassadors and go-betweens (except between elves and humans, since each side suspects the half-elf of favoring the other).",
  },
  {:racial_trait_id => 24,
   :description => "The half-elves are uncommon. They don't exist in every world of D&D, and even where they are found. They are less widespread than dwarves, elves, halfings, and humans.",
  },
  {:racial_trait_id => 24,
   :description => "In the cosmopolitan cities of the D&D multiverse, most people hardly look twice at members of even the most exotic races. But the small towns and villages that dot the countryside are different. The common folk aren't accustomed to seeing members of these races, and they react accordingly.",
  },
  {:racial_trait_id => 24,
   :description => "Although many people have never seen a half-elf, virtually everyone knows they exist. A half-elf stranger's arrival is followed by gossip behind the half-elf's back and stolen glances across the common room, rather than any confrontation or open curiosity.",
  },
  {:racial_trait_id => 25,
   :description => "Half-elves use either human or elven naming conventions. As if to emphasize that they don't really fit in to either society, half-elves raised among humans are often given elven names, and those raised among elves often take human names.",
  },
  {:racial_trait_id => 26,
   :description => "The diminutive halflings survive in a world full of larger creatures by avoiding notice or, barring that, avoiding offense. Standing about 3 feet tall, they appear re1atively harmless and so have managed to survive for centuries in the shadow of empires and on the edges of wars and political strife. They are inclined to be stout, weighing between 40 and 45 pounds.",
  },
  {:racial_trait_id => 26,
   :description => "Halflings' skin ranges from tan to pale with a ruddy cast, and their hair is usually brown or sandy brown and wavy. They have brown or hazel eyes. Halfling men often sport long sideburns, but beards are rare among them and mustaches even more so. They like to wear simple, comfortable, and practical clothes, favoring bright colors.",
  },
  {:racial_trait_id => 26,
   :description => "Halfling practicality extends beyond their clothing. They're concerned with basic needs and simple pleasures and have little use for ostentation. Even the wealthiest of halflings keep their treasures locked in a cellar rather than on display for all to see. They have a knack for finding the most straightforward solution to a problem, and have little patience for dithering.",
  },
  {:racial_trait_id => 27,
   :description => "Halflings are an affable and cheerful people. They cherish the bonds of family and friendship as well as the comforts of hearth and home, harboring few dreams of gold or glory. Even adventurers among them usually venture into the world for reasons of community, friendship, wanderlust, or curiosity. They lave discovering new things, even simple things, such as an exotic food or an unfamiliar style of c1othing.",
  },
  {:racial_trait_id => 27,
   :description => "Halflings are easily moved to pity and hate to see any living thing suffer. They are generous, happily sharing what they have even in lean times.",
  },
  {:racial_trait_id => 28,
   :description => "Halflings are adept at fitting into a community of humans, dwarves, or elves, making themselves valuable and welcome. The combination of their inherent stealth and their unassuming nature helps halflings to avoid unwanted attention.",
  },
  {:racial_trait_id => 28,
   :description => "Halflings work readily with others, and they are loyal to their friends, whether halfling or otherwise. They can display remarkable ferocity when their friends, families, or communities are threatened.",
  },
  {:racial_trait_id => 29,
   :description => "Most halflings live in small, peaceful communities with large farms and well-kept graves. They rarely build kingdoms of their own or even hold much land beyond their quiet shires. They typically don't recognize any sort of halfling nobility or royalty, instead looking to family elders to guide them. Families preserve their traditional ways despite the rise and fall of empires.",
  },
  {:racial_trait_id => 29,
   :description => "Many halflings live among other races, where the halflings' hard work and loyal outlook offer them abundant rewards and creature comforts. Some halfling communities travel as a way of life, driving wagons or guiding boats from place to place and maintaining no permanent home.",
  },
  {:racial_trait_id => 30,
   :description => "Halflings usually set out on the adventurer's path lo defend their communities, support their friends, or explore a wide and wonder-filled world. For them, adventuring is less a career than an opportunity or sometimes a necessity.",
  },
  {:racial_trait_id => 31,
   :description => "Halflings try to get along with everyone else and are loath to make sweeping generalizations-especially negative ones.",
  },
  {:racial_trait_id => 31,
   :description => 'Dwarves: "Dwarves make loyal friends, and you can count on them to keep their word. But would it hurt them to smile once in a while."',
  },
  {:racial_trait_id => 31,
   :description => 'Elves: "They\'re so beautiful! Their faces, their music, their grace and all. It\'s like they stepped out of a wonderful dream. But there\'s no telling what\'s going on behind their smiling faces-surely more than they ever let on."',
  },
  {:racial_trait_id => 31,
   :description => 'Humans: "Humans are a lot like us, really. At least some of them are. Step out of the castles and keeps, go talk to the farmers and herders and you\'ll find good, solid folk. Not that there\'s anything wrong with the barons and soldiers-you have to admire their conviction. And by protecting their own lands, they protect us as well."',
  },
  {:racial_trait_id => 32,
   :description => "A halfling has a given name, a family name, and possibly a nickname. Family names are often nicknames that stuck so tenaciously they have been passed down through the generations.",
  },
  {:racial_trait_id => 33,
   :description => "The diminutive halflings survive in a world full of larger creatures by avoiding notice or, barring that, avoiding offense. Standing about 3 feet tall, they appear re1atively harmless and so have managed to survive for centuries in the shadow of empires and on the edges of wars and political strife. They are inclined to be stout, weighing between 40 and 45 pounds.",
  },
  {:racial_trait_id => 33,
   :description => "Halflings' skin ranges from tan to pale with a ruddy cast, and their hair is usually brown or sandy brown and wavy. They have brown or hazel eyes. Halfling men often sport long sideburns, but beards are rare among them and mustaches even more so. They like to wear simple, comfortable, and practical clothes, favoring bright colors.",
  },
  {:racial_trait_id => 33,
   :description => "Halfling practicality extends beyond their clothing. They're concerned with basic needs and simple pleasures and have little use for ostentation. Even the wealthiest of halflings keep their treasures locked in a cellar rather than on display for all to see. They have a knack for finding the most straightforward solution to a problem, and have little patience for dithering.",
  },
  {:racial_trait_id => 34,
   :description => "Halflings are an affable and cheerful people. They cherish the bonds of family and friendship as well as the comforts of hearth and home, harboring few dreams of gold or glory. Even adventurers among them usually venture into the world for reasons of community, friendship, wanderlust, or curiosity. They lave discovering new things, even simple things, such as an exotic food or an unfamiliar style of c1othing.",
  },
  {:racial_trait_id => 24,
   :description => "Halflings are easily moved to pity and hate to see any living thing suffer. They are generous, happily sharing what they have even in lean times.",
  },
  {:racial_trait_id => 35,
   :description => "Halflings are adept at fitting into a community of humans, dwarves, or elves, making themselves valuable and welcome. The combination of their inherent stealth and their unassuming nature helps halflings to avoid unwanted attention.",
  },
  {:racial_trait_id => 35,
   :description => "Halflings work readily with others, and they are loyal to their friends, whether halfling or otherwise. They can display remarkable ferocity when their friends, families, or communities are threatened.",
  },
  {:racial_trait_id => 36,
   :description => "Most halflings live in small, peaceful communities with large farms and well-kept graves. They rarely build kingdoms of their own or even hold much land beyond their quiet shires. They typically don't recognize any sort of halfling nobility or royalty, instead looking to family elders to guide them. Families preserve their traditional ways despite the rise and fall of empires.",
  },
  {:racial_trait_id => 36,
   :description => "Many halflings live among other races, where the halflings' hard work and loyal outlook offer them abundant rewards and creature comforts. Some halfling communities travel as a way of life, driving wagons or guiding boats from place to place and maintaining no permanent home.",
  },
  {:racial_trait_id => 37,
   :description => "Halflings usually set out on the adventurer's path lo defend their communities, support their friends, or explore a wide and wonder-filled world. For them, adventuring is less a career than an opportunity or sometimes a necessity.",
  },
  {:racial_trait_id => 38,
   :description => "Halflings try to get along with everyone else and are loath to make sweeping generalizations-especially negative ones.",
  },
  {:racial_trait_id => 38,
   :description => 'Dwarves: "Dwarves make loyal friends, and you can count on them to keep their word. But would it hurt them to smile once in a while."',
  },
  {:racial_trait_id => 38,
   :description => 'Elves: "They\'re so beautiful! Their faces, their music, their grace and all. It\'s like they stepped out of a wonderful dream. But there\'s no telling what\'s going on behind their smiling faces-surely more than they ever let on."',
  },
  {:racial_trait_id => 38,
   :description => 'Humans: "Humans are a lot like us, really. At least some of them are. Step out of the castles and keeps, go talk to the farmers and herders and you\'ll find good, solid folk. Not that there\'s anything wrong with the barons and soldiers-you have to admire their conviction. And by protecting their own lands, they protect us as well."',
  },
  {:racial_trait_id => 39,
   :description => "A halfling has a given name, a family name, and possibly a nickname. Family names are often nicknames that stuck so tenaciously they have been passed down through the generations.",
  },
  {:racial_trait_id => 40,
   :description => "Half-orcs' grayish pigmentation, sloping foreheads, jutting jaws, prominent teeth, and lowering builds make their orcish heritage plain for all lo see. Half-orcs stand between 6 and 7 feet tall and usually weigh between 180 and 250 pounds.",
  },
  {:racial_trait_id => 40,
   :description => "Orcs regard battle scars as tokens of pride and ornamental scars as things of beauty. Other scars, though, mark an orc or half-orc as a former slave or a disgraced exile. Any half-orc who has lived among or near orcs has scars, whether they are marks of humiliation or of pride, recounting their past exploits and injuries. Such a half-orc living among humans might display these sears proudly or hide them in shame.",
  },
  {:racial_trait_id => 41,
   :description => "The one-eyed god Gruumsh created the orcs, and even those orcs who turn away from his worship can't fully escape his influence. The same is true of half-orcs, though their human blood moderates the impact of their orcish heritage. Some half-orcs hear the whispers of Gruumsh in their dreams, calling them lo unleash the rage that simmers within them. Others feel Gruumsh's exultation when they join in melee vombat-and either exult along with him or shiver with fear and loathing. Half-orcs are not evil by nature, but evil does lurk within them, whether they embrace it or rebel against it.",
  },
  {:racial_trait_id => 41,
   :description => "Beyond the rage of Gruumsh, half-orcs feel emotion powerfully. Rage doesn't just quicken their pulse, it makes their bodies burn. An insult stings like acid, and sadness saps their strength. But they laugh loudly and heartily, and simple bodily pleasures-feasting, drinking, wrestling, drumming, and wild dancing-fill their hearts with joy. They tend to be short-tempered and sometimes sullen, more inclined to action than contemplation and to fighting than arguing. The most accomplished half-orcs are those with enough self-control to get by in a civilized land.",
  },
  {:racial_trait_id => 42,
   :description => "Half-orcs most often live among orcs. Of the other races, humans are most likely to accept half-orcs, and half-orcs almost always live in human lands when not living among orc tribes. Whether proving themselves among rough barbarian tribes or scrambling to survive in the slums of larger cities, half-orcs gel by on their physical might, their endurance, and the sheer determination they inherit from their human ancestry.",
  },
  {:racial_trait_id => 43,
   :description => "Each half-orc finds a way to gain acceptance from those who hate orcs. Some are reserved, trying not to draw attention to themselves. A few demonstrate piety and good-heartedness as publicly as they can (whether or not such demonstrations are genuine). And some simply try to be so tough that others just avoid them.",
  },
  {:racial_trait_id => 44,
   :description => "The half-orcs are uncommon. They don't exist in every world of D&D, and even where they are found, they are less widespread than dwarves, elves, halfings, and humans.",
  },
  {:racial_trait_id => 44,
   :description => "In the cosmopolitan cities of the D&D multiverse, most people hardly look twice at members of even the most exotic races. But the small towns and villages that dot the countryside are different. The common folk aren't accustomed to seeing members of these races, and they react accordingly.",
  },
  {:racial_trait_id => 44,
   :description => "It's usually safe to assume that a half-orc is belligerent and quick to anger, so people watch themselves around an unfamiliar half-orc. Shopkeepers might surreptitiously hide valuable or fragile goods when a half-orc comes in, and people slowly clear out of a tavern, assuming a fight will break out soon.",
  },
  {:racial_trait_id => 45,
   :description => "Half-orcs usually have names appropriate to the culture in which they were raised. A half-orc who wants to fit in among humans might trade an orc name for a human name. Some half-orcs with human names decide to adopt a guttural orc name because they think it makes them more intimidating.",
  },
  {:racial_trait_id => 46,
   :description => "With their unearthly grace and fine features, elves appear hauntingly beautiful to humans and members of many other races. They are slightly shorter than humans on average, ranging from well under 5 feet tall to just over 6 feet. They are more slender than humans, weighing only 100 to 145 pounds. Males and females are about the same height, and males are only marginally heavier than females.",
  },
  {:racial_trait_id => 46,
   :description => "Elves' coloration encompasses the normal human range and also includes skin in shades of copper, bronze, and almost bluish-white, hair of green or blue, and eyes like pools of liquid gold or silver. Elves have no facial and little body hair. They favor elegant clothing in bright colors, and they enjoy simple yet lovely jewelry,",
  },
  {:racial_trait_id => 47,
   :description => "Elves can live well over 700 years, giving them a broad perspective on events that might trouble the shorter-lived races more deeply, They are more often amused than excited, and more likely to be curious than greedy. They tend to remain aloof and unfazed by petty happenstance. When pursuing a goal, however, whether adventuring on a mission or learning a new skill or art, elves can be focused and relentless. They are slow to make friends and enemies, and even slower to forget them. They reply to petty insults with disdain and to serious insults with vengeance.",
  },
  {:racial_trait_id => 47,
   :description => "Like the branches of a young tree, elves are flexible in the face of danger. They trust in diplomacy and compromise to resolve differences before they escalate to violence. They have been known to retreat from intrusions into their woodland homes, confident that they can simply wait the invaders out. But when the need arises, elves reveal a stern martial side, demonstrating skill with sword, bow, and strategy.",
  },
  {:racial_trait_id => 48,
   :description => "Most elves dwell in small forest villages hidden among the trees. Elves hunt game, gather food, and grow vegetables, and their skill and magic allow them to support themselves without the need for clearing and plowing land. They are talented artisans, crafting finely worked clothes and art objects. Their contact with outsiders is usually limited, though a few elves make a good living by trading crafted items for metals (which they have no interest in mining).",
  },
  {:racial_trait_id => 48,
   :description => "Elves encountered outside their own lands are commonly traveling minstrels, artists, or sages. Human nobles compete for the services of elf instructors to teach swordplay or magic to their children.",
  },
  {:racial_trait_id => 49,
   :description => "Elves take up adventuring out of wanderlust. Since they are so long-lived, they can enjoy centuries of exploration and discovery. They dislike the pace of human society, which is regimented from day to day but constantly changing over decades, so they find careers that let them travel freely and set their own pace. Elves also enjoy exercising their martial prowess or gaining greater magical power, and adventuring allows them to do so. Some might join with rebels fighting against oppression, and others might become champions of moral causes.",
  },
  {:racial_trait_id => 50,
   :description => "Although they can be haughty, elves are generally gracious even to those who fall short of their high expectations- which is most non-elves. 5till, they can find good in just about anyone.",
  },
  {:racial_trait_id => 50,
   :description => "Dwarves: \"Dwarves are dull, clumsy oafs. But what they lack in humor, sophistication, and manners, they make up in valor. And I must admit, their best smiths produce art that approaches elven quality.\"",
  },
  {:racial_trait_id => 50,
   :description => "Halflings: \"Halflings are people of simple pleasures, and that is not a quality to scorn. They're good folk, they care for each other and tend their gardens, and they have proven themselves tougher than they seem when the need arises.\"",
  },
  {:racial_trait_id => 50,
   :description => "Humans: \"All that haste, their ambition and drive to accomplish something before their brief lives pass away-human endeavors seem 50 futile sometimes. But then you look at what they have accomplished, and you have to appreciate their achievements. If only they could slow down and learn some refinement.\"",
  },
  {:racial_trait_id => 51,
   :description => "Elves are considered children until they declare themselves adults, some time after the hundredth birthday, and before this period they are called by child names.",
  },
  {:racial_trait_id => 51,
   :description => "On declaring adulthood, an elf selects an adult name, although those who knew him or her as a youngster might continue to use the child name. Each elf's adult name is a unique creation, though It might reflect the names of respected individuals or other family members. Little distinction exists between male names and female names; the groupings here reflect only general tendencies. In addition, every elf bears a family name, typically a combination of other Elvish words. Some elves traveling among humans translate their family names into Common, but others retain the Elvish version.",
  },
  {:racial_trait_id => 52,
   :description => "Bold and hardy, dwarves are known as skilled warriors, miners, and workers of stone and metal. Though they stand well under 5 feet tall, dwarves are so broad and compact that they can weigh as much as a human standing nearly two feet taller. Their courage and endurance are also easily a match for any of the larger folk.",
  },
  {:racial_trait_id => 52,
   :description => "Dwarven skin ranges from deep brown to a paler hue tinged with red, but the most common shades are light brown or deep tan, like certain tones of earth. Their hair, worn long but in simple styles, is usually black, gray, or brown, though paler dwarves often have red hair. Male dwarves value their beards highly and groom them carefully.",
  },
  {:racial_trait_id => 53,
   :description => "Dwarves can live to be more than 400 years old, so the oldest living dwarves often remember a very different world. For example, some of the oldest dwarves living in Citadel Felbarr (in the world of the Forgotten Realms) can recall the day, more than three centuries ago, when orcs conquered the fortress and drove them into an exile that lasted over 250 years. This longevity grants them a perspective on the world that shorter-lived races such as humans and halflings lack.",
  },
  {:racial_trait_id => 53,
   :description => "Dwarves are solid and enduring like the mountains they love, weathering the passage of centuries with stoic endurance and little change. They respect the traditions of their clans, tracing their ancestry back to the founding of their most ancient strongholds in the youth of the world, and don't abandon those traditions lightly. Part of those traditions is devotion to the gods of the dwarves, who uphold the dwarven ideals of industrious labor, skill in battle, and devotion to the forge.",
  },
  {:racial_trait_id => 53,
   :description => "Individual dwarves are determined and loyal, true to their word and decisive in action, sometimes to the point of stubbornness. Many dwarves have a strong sense of justice, and they are slow to forget wrongs they have suffered. A wrong done to one dwarf is a wrong done to the dwarf's entire clan, so what begins as one dwarf's hunt for vengeance can become a full-blown clan feud.",
  },
  {:racial_trait_id => 54,
   :description => "Dwarven kingdoms stretch deep beneath the mountains where the dwarves mine gems and precious metals and forge items of wonder. They love the beauty and artistry of precious metals and fine jewelry, and in some dwarves this love festers into avarice. Whatever wealth they can't find in their mountains, they gain through trade. They dislike boats, so enterprising humans and halflings frequently handle trade in dwarven goods along water routes. Trustworthy members of other races are welcome in dwarf settlements, though some areas are off limits even to them.",
  },
  {:racial_trait_id => 54,
   :description => "The chief unit of dwarven society is the clan, and dwarves highly value social standing. Even dwarves who live far from their own kingdoms cherish their clan identities and affiliations, recognize related dwarves, and invoke their ancestors' names in oaths and curses. To be clanless is the worst fate that can befall a dwarf.",
  },
  {:racial_trait_id => 54,
   :description => "Dwarves in other lands are typically artisans, especially weaponsmiths, armorers, and jewelers. Some become mercenaries or bodyguards, highly sought after for their courage and loyalty.",
  },
  {:racial_trait_id => 55,
   :description => "Dwarves who take up the adventuring life might be motivated by a desire for treasure-for its own sake, for a specific purpose, or even out of an altruistic desire to help others. Other dwarves are driven by the command or inspiration of a deity, a direct calling or simply a desire to bring glory to one of the dwarf gods. Clan and ancestry are also important motivators. A dwarf might seek to restore a clan's lost honor, avenge an ancient wrong the clan suffered, or earn a new place within the clan after having been exiled, or a dwarf might search for the axe wielded by a mighty ancestor, lost on the field of battle centuries ago.",
  },
  {:racial_trait_id => 56,
   :description => "Dwarves get along passably well with most other races. \"The difference between an acquaintance and a friend is about a hundred years,\" is a dwarf saying that might be hyperbole, but certainly points to how difficult it can be for a member of a short-lived race like humans to earn a dwarf's trust.",
  },
  {:racial_trait_id => 56,
   :description => "Elves: \"It's not wise to depend on the elves. No telling what an elf will do next; when the hammer meets the orc's head, they're as apt to start singing as to pull out a sword. They're flighty and frivolous. Two things to be said for them, though: They don't have many smiths, but the ones they have do very fine work. And when orcs or goblins come screaming down out of the mountains, an elf's good to have at your back. Not as good as a dwarf, maybe, but no doubt they hate the orcs as much as we do.\"",
  },
  {:racial_trait_id => 56,
   :description => "Halflings: \"Sure, they're pleasant folk. But show me a halfling hero. An empire, a triumphant army. Even a treasure for the ages made by halfling hands. Nothing. How can you take them seriously?\"",
  },
  {:racial_trait_id => 56,
   :description => "Humans: \"You take the time to get to know a human, and by then the human's on her deathbed. If you're lucky, she's got kin-a daughter or granddaughter, maybe-who's got hands and heart as good as hers. That's when you can make a human friend. And watch them go. They set their hearts on something, they'll get it, whether it's a dragon's hoard or an empire's throne. You have to admire that kind of dedication, even if it gets them in trouble more often than not.\"",
  },
  {:racial_trait_id => 57,
   :description => "A dwarf's name is granted by a c1an elder, in accordance with tradition, Every proper dwarven name has been used and reused down through the generations, A dwarf's name belongs to the c1an, not to the individual. A dwarf who misuses or brings shame to a c1an name is stripped of the name and forbidden by law to use any dwarven name in its place,",
  },
  {:racial_trait_id => 58,
   :description => "With their penchant for migration and conquest. humans are more physically diverse than other common races. There is no typical human. An individual can stand from 5 feet to a little over 6 feet tall and weigh from 125 to 250 pounds. Human skin shades range from nearly black to very pale. and hair colors from black to blond (curly. kinky. or straight); males might sport facial hair that is sparse or thick. A lot of humans have a dash of nonhuman blood. revealing hints of elf. ore, or other lineages. Humans reach adulthood in their late teens and rarely live even a single century.",
  },
  {:racial_trait_id => 59,
   :description => "Humans are the most adaptable and ambitious people among the common races. They have widely varying tastes, morals, and customs in the many different lands where they have settled. When they settle, though, they stay: they build cities to last for the ages, and great kingdoms that can persist for long centuries. An individual human might have a relatively short life span, but a human nation or culture preserves traditions with origins far beyond the reach of any single human's memory. They live fully in the present-making them well suited to the adventuring life-but also plan for the future, striving to leave a lasting legacy. Individually and as a group, humans are adaptable opportunists, and they stay alert to changing political and social dynamics.",
  },
  {:racial_trait_id => 60,
   :description => "Just as readily as they mix with each other, humans mingle with members of other races. They get along with almost everyone, though they might not be close to many. Humans serve as ambassadors, diplomats, magistrates, merchants, and functionaries of all kinds.",
  },
  {:racial_trait_id => 60,
   :description => "Dwarves: \"They're stout folk, stalwart friends, and true to their word. Their greed for gold is their downfall, though.\"",
  },
  {:racial_trait_id => 60,
   :description => "Elves: \"It's best not to wander into elven woods. They don't like intruders, and you'll as likely be bewitched as peppered with arrows. 5till, if an elf can get past that damned racial pride and actually treat you like an equal, you can learn a lot from them.\"",
  },
  {:racial_trait_id => 60,
   :description => "Halflings: \"It's hard to beat a meal in a halfling home, as long as you don't crack your head on the ceiling-good food and good stories in front of a nice, warm fire. If halflings had a shred of ambition, they might really amount to something.\"",
  },
  {:racial_trait_id => 61,
   :description => "Where a single elf or dwarf might take on the responsibility of guarding a special location or a powerful secret, humans found sacred orders and institutions for such purposes. While dwarf c1ans and halfling elders pass on the ancient traditions to each new generation, human temples, governments, libraries, and codes of law fix their traditions in the bedrock of history. Humans dream of immortality, but (except for those few who seek undeath or divine ascension to escape death's c1utches) they achieve it by ensuring that they will be remembered when they are gone.",
  },
  {:racial_trait_id => 61,
   :description => "Although some humans can be xenophobic, in general their societies are inclusive. Human lands welcome large numbers of nonhumans compared to the proportion of humans who live in nonhuman lands.",
  },
  {:racial_trait_id => 62,
   :description => "Humans who seek adventure are the most daring and ambitious members of a daring and ambitious race. They seek to earn glory in the eyes of their fellows by amassing power, wealth, and fame. More than other people, humans champion causes rather than territories or groups.",
  },
  {:racial_trait_id => 63,
   :description => "Having so much more variety than other cultures, humans as a whole have no typical names. Some human parents give their children names from other languages, such as Dwarvish or Elvish (pronounced more or less correctly), but most parents give names that are linked to their region's culture or to the naming traditions of their ancestors.",
  },
  {:racial_trait_id => 63,
   :description => "The material culture and physical characteristics of humans can change wildly from region to region. In the Forgotten Realms, for example, the clothing, architecture, cuisine, music, and literature are different in the northwestern lands of the Silver Marches than in distant Turmish or Impiltur to the east-and even more distinctive in far-off Kara-Tur. Human physical characteristics, though, vary according to the ancient migrations of the earliest humans, so that the humans of the Silver Marches have every possible variation of coloration and features.",
  },
  {:racial_trait_id => 63,
   :description => "In the Forgotten Realms, nine human ethnic groups are widely recognized, though over a dozen others are found in more localized areas of Faerun. These groups, and the typical names of their members, can be used as inspiration no matter which world your human is in.",
  },
  {:racial_trait_id => 63,
   :description => "Calishite: Shorter and slighter in build than most other humans, Calishites have dusky brown skin, hair, and eyes. They're found primarily in southwest Faerun.",
  },
  {:racial_trait_id => 63,
   :description => "Chondathan: Chondathans are slender, tawny-skinned folk with brown hair that ranges from almost blond to almost black. Most are tall and have green or brown eyes, but these trails are hardly universal. Humans of Chondathan descent dominate the central lands of Faerun, around the Inner Sea.",
  },
  {:racial_trait_id => 63,
   :description => "Damaran: Found primarily in the northwest of Faerun, Damarans are of moderate height and build, with skin hues ranging from tawny to fair. Their hair is usually brown or black, and their eye color varies widely, though brown is most common.",
  },
  {:racial_trait_id => 63,
   :description => "Illuskan: Illuskans are tall, fair-skinned folk with blue or steely gray eyes. Most have raven-black hair, but those who inhabit the extreme northwest have blond, red, or light brown hair.",
  },
  {:racial_trait_id => 63,
   :description => "Mulan: Dominant in the eastern and southeastern shores of the Inner Sea, the Mulan are generally tall, slim, and amber-skinned, with eyes of hazel or brown. Their hair ranges from black to dark brown, but in the lands where the Mulan are most prominent, nobles and many other Mulan shave off all their hair.",
  },
  {:racial_trait_id => 63,
   :description => "Rashemi: Most often found east of the Inner Sea and often intermingled with the Mulan, Rashemis tend to be short, stout, and muscular. They usually have dusky skin, dark eyes, and thick black hair.",
  },
  {:racial_trait_id => 63,
   :description => "Shou: The Shou are the most numerous and powerful ethnic group in Kara-Tur, far to the east of Faerun. They are yellowish-bronze in hue, with black hair and dark eyes. Shou surnames are usually presented before the given name.",
  },
  {:racial_trait_id => 63,
   :description => "Tethyrian: Widespread along the entire Sword Coast at the western edge of Faerun, Tethyrians are of medium build and height, with dusky skin that tends to grow fairer the farther north they dwell. Their hair and eye color varies widely, but brown hair and blue eyes are the most common. Tethyrians primarily use Chondathan names.",
  },
  {:racial_trait_id => 63,
   :description => "Turami: Native to the southern shore of the Inner Sea, the Turami people are generally tall and muscular, with dark mahogany skin, curly black hair, and dark eyes.",
  },
  {:racial_trait_id => 64,
   :description => "Bold and hardy, dwarves are known as skilled warriors, miners, and workers of stone and metal. Though they stand well under 5 feet tall, dwarves are so broad and compact that they can weigh as much as a human standing nearly two feet taller. Their courage and endurance are also easily a match for any of the larger folk.",
  },
  {:racial_trait_id => 64,
   :description => "Dwarven skin ranges from deep brown to a paler hue tinged with red, but the most common shades are light brown or deep tan, like certain tones of earth. Their hair, worn long but in simple styles, is usually black, gray, or brown, though paler dwarves often have red hair. Male dwarves value their beards highly and groom them carefully.",
  },
  {:racial_trait_id => 65,
   :description => "Dwarves can live to be more than 400 years old, so the oldest living dwarves often remember a very different world. For example, some of the oldest dwarves living in Citadel Felbarr (in the world of the Forgotten Realms) can recall the day, more than three centuries ago, when orcs conquered the fortress and drove them into an exile that lasted over 250 years. This longevity grants them a perspective on the world that shorter-lived races such as humans and halflings lack.",
  },
  {:racial_trait_id => 65,
   :description => "Dwarves are solid and enduring like the mountains they love, weathering the passage of centuries with stoic endurance and little change. They respect the traditions of their clans, tracing their ancestry back to the founding of their most ancient strongholds in the youth of the world, and don't abandon those traditions lightly. Part of those traditions is devotion to the gods of the dwarves, who uphold the dwarven ideals of industrious labor, skill in battle, and devotion to the forge.",
  },
  {:racial_trait_id => 65,
   :description => "Individual dwarves are determined and loyal, true to their word and decisive in action, sometimes to the point of stubbornness. Many dwarves have a strong sense of justice, and they are slow to forget wrongs they have suffered. A wrong done to one dwarf is a wrong done to the dwarf's entire clan, so what begins as one dwarf's hunt for vengeance can become a full-blown clan feud.",
  },
  {:racial_trait_id => 66,
   :description => "Dwarven kingdoms stretch deep beneath the mountains where the dwarves mine gems and precious metals and forge items of wonder. They love the beauty and artistry of precious metals and fine jewelry, and in some dwarves this love festers into avarice. Whatever wealth they can't find in their mountains, they gain through trade. They dislike boats, so enterprising humans and halflings frequently handle trade in dwarven goods along water routes. Trustworthy members of other races are welcome in dwarf settlements, though some areas are off limits even to them.",
  },
  {:racial_trait_id => 66,
   :description => "The chief unit of dwarven society is the clan, and dwarves highly value social standing. Even dwarves who live far from their own kingdoms cherish their clan identities and affiliations, recognize related dwarves, and invoke their ancestors' names in oaths and curses. To be clanless is the worst fate that can befall a dwarf.",
  },
  {:racial_trait_id => 66,
   :description => "Dwarves in other lands are typically artisans, especially weaponsmiths, armorers, and jewelers. Some become mercenaries or bodyguards, highly sought after for their courage and loyalty.",
  },
  {:racial_trait_id => 67,
   :description => "Dwarves who take up the adventuring life might be motivated by a desire for treasure-for its own sake, for a specific purpose, or even out of an altruistic desire to help others. Other dwarves are driven by the command or inspiration of a deity, a direct calling or simply a desire to bring glory to one of the dwarf gods. Clan and ancestry are also important motivators. A dwarf might seek to restore a clan's lost honor, avenge an ancient wrong the clan suffered, or earn a new place within the clan after having been exiled, or a dwarf might search for the axe wielded by a mighty ancestor, lost on the field of battle centuries ago.",
  },
  {:racial_trait_id => 68,
   :description => "Dwarves get along passably well with most other races. \"The difference between an acquaintance and a friend is about a hundred years,\" is a dwarf saying that might be hyperbole, but certainly points to how difficult it can be for a member of a short-lived race like humans to earn a dwarf's trust.",
  },
  {:racial_trait_id => 68,
   :description => "Elves: \"It's not wise to depend on the elves. No telling what an elf will do next; when the hammer meets the orc's head, they're as apt to start singing as to pull out a sword. They're flighty and frivolous. Two things to be said for them, though: They don't have many smiths, but the ones they have do very fine work. And when orcs or goblins come screaming down out of the mountains, an elf's good to have at your back. Not as good as a dwarf, maybe, but no doubt they hate the orcs as much as we do.\"",
  },
  {:racial_trait_id => 68,
   :description => "Halflings: \"Sure, they're pleasant folk. But show me a halfling hero. An empire, a triumphant army. Even a treasure for the ages made by halfling hands. Nothing. How can you take them seriously?\"",
  },
  {:racial_trait_id => 68,
   :description => "Humans: \"You take the time to get to know a human, and by then the human's on her deathbed. If you're lucky, she's got kin-a daughter or granddaughter, maybe-who's got hands and heart as good as hers. That's when you can make a human friend. And watch them go. They set their hearts on something, they'll get it, whether it's a dragon's hoard or an empire's throne. You have to admire that kind of dedication, even if it gets them in trouble more often than not.\"",
  },
  {:racial_trait_id => 69,
   :description => "A dwarf's name is granted by a c1an elder, in accordance with tradition, Every proper dwarven name has been used and reused down through the generations, A dwarf's name belongs to the c1an, not to the individual. A dwarf who misuses or brings shame to a c1an name is stripped of the name and forbidden by law to use any dwarven name in its place,",
  },
  {:racial_trait_id => 70,
   :description => "A gnome's energy and enthusiasm for living shines through every inch of his or her tiny body. Gnomes average slightly over 3 feet tall and weigh 40 to 45 pounds. Their tan or brown faces are usually adorned with broad smiles (beneath their prodigious noses), and their bright eyes shine with excitement. Their air hair has a tendency to stick out in every direction, as if expressing the gnome's insatiable interest in everything around.",
  },
  {:racial_trait_id => 70,
   :description => "A gnome's personality is writ large in his or her appearance. A male gnome's beard, in contrast to his wild hair, is kept carefully trimmed but often styled into curious forks or neat points. A gnome's clothing, though usually made in modest earth tones, is elaborately decorated with embroidery, embossing, or gleaming jewels.",
  },
  {:racial_trait_id => 71,
   :description => "As far as gnomes are concerned, being alive is a wonderful thing, and they squeeze every ounce of enjoyment out of their three to five centuries of life. Humans might wonder about getting bored over the course of such a long life, and elves take plenty of time to savor the beauties of the world in their long years, but gnomes seem to worry that even with all that time, they can't get in enough of the things they want to do and see.",
  },
  {:racial_trait_id => 71,
   :description => "Gnomes speak as if they can't get the thoughts out of their heads fast enough. Even as they offer ideas and opinions on a range of subjects, they still manage to listen carefully to others, adding the appropriate exclamations of surprise and appreciation along the way.",
  },
  {:racial_trait_id => 71,
   :description => "Though gnomes love jokes of all kinds, particularly puns and pranks, they're just as dedicated to the more serious tasks they undertake, Many gnomes are skilled engineers, alchemists, tinkers, and inventors, They're willing to make mistakes and laugh at themselves in the process of perfecting what they do, taking bold (sometimes foolhardy) risks and dreaming large,",
  },
  {:racial_trait_id => 72,
   :description => "Gnomes make their homes in hilly, wooded lands. They live underground but get more fresh air than dwarves do, enjoying the natural, living world on the surface whenever they can, Their homes are well hidden by both clever construction and simple illusions. Welcome visitors are quickly ushered into the bright, warm burrows. Those who are not welcome are unlikely to find the burrows in the first place,",
  },
  {:racial_trait_id => 72,
   :description => "Gnomes who settle in human lands are commonly gem cutters, engineers, sages, or tinkers. Some human families retain gnome tutors, ensuring that their pupils enjoy a mix of serious learning and delighted enjoyment. A gnome might tutor several generations of a single human family over the course of his or her long life.",
  },
  {:racial_trait_id => 73,
   :description => "The gnome are uncommon. They don't exist in every world of D&D, and even where they are found. They are less widespread than dwarves, elves, halfings, and humans.",
  },
  {:racial_trait_id => 73,
   :description => "In the cosmopolitan cities of the D&D multiverse, most people hardly look twice at members of even the most exotic races. But the small towns and villages that dot the countryside are different. The common folk aren't accustomed to seeing members of these races, and they react accordingly.",
  },
  {:racial_trait_id => 73,
   :description => "Gnomes don't look like a threat and can quickly disarm suspicion with good humor. The common folk are often curious about gnomes, likely never having seen one before, but they are rarely hostile or fearful.",
  },
  {:racial_trait_id => 74,
   :description => "Curious and impulsive, gnomes might take up adventuring as a way to see the world or for the love of exploring. As lovers of gems and other fine items, some gnomes take to adventuring as a quick, if dangerous, path to wealth. Regardless of what spurs them lo adventure, gnomes who adopt this way of life eke as much enjoyment out of it as they do out of any other activity they undertake, sometimes to the great annoyance of their adventuring companions.",
  },
  {:racial_trait_id => 75,
   :description => "A third subrace of gnomes, the deep gnomes (or svirfneblin), live in small communities scattered in the Underdark. Unlike the duergar and the drow, svirfneblin are as good as their surface cousins. However, their humor and enthusiasm are dampened by their oppressive environment, and their inventive expertise is directed mostly toward stonework.",
  },
  {:racial_trait_id => 76,
   :description => "It's rare for a gnome to be hostile or malicious unless he or she has suffered a grievous injury. Gnomes know that most races don't share their sense of humor, but they enjoy anyone's company just as they enjoy everything else they set out to do.",
  },
  {:racial_trait_id => 77,
   :description => "Gnomes love names, and most have half a dozen or so. A gnome's mother, father, clan elder, aunts, and uncles each give the gnome a name, and various nicknames from just about everyone else might or might not stick over time. Gnome names are typically variants on the names of ancestors or distant relatives, though some are purely new inventions. When dealing with humans and others who are 'stuffy' about names, a gnome learns to use no more than three names: a personal name, a clan name, and a nickname, choosing the one in each category that's the most fun to say.",
  },
  {:racial_trait_id => 78,
   :description => "Tieflings are derived from human bloodlines, and in the broadest possible sense, they still look human. However, their infernal heritage has left a clear imprint on their appearance. Tieflings have large horns that take any of a variety of shapes: some have curling horns like a ram, others have straight and tall horns like a gazelle's, and some spiral upward like an antelopes' horns. They have thick tails, four to five feet long, which lash or coil around their legs when they get upset or nervous. Their canine teeth are sharply pointed, and their eyes are solid colors-black, red, white, silver, or gold-with no visible sclera or pupil. Their skin tones cover the full range of human coloration, but also include various shades of red. Their hair, cascading down from behind their horns, is usually dark, from black or brown to dark red, blue, or purple.",
  },
  {:racial_trait_id => 79,
   :description => "Tieflings subsist in small minorities found mostly in human cities or towns, often in the roughest quarters of those places, where they grow up to be swindlers, thieves, or crime lords, Sometimes they live among other minority populations in enclaves where they are treated with more respect.",
  },
  {:racial_trait_id => 79,
   :description => "Lacking a homeland, tieflings know that they have to make their own way in the world and that they have to be strong to survive, They are not quick to trust anyone who claims to be a friend. but when a tiefling's companions demonstrate that they trust him or her, the tiefling learns to extend the same trust to them, And once a tiefling gives someone loyalty, the tiefling is a firm friend or ally for life,",
  },
  {:racial_trait_id => 80,
   :description => "People tend to be suspicious of tieflings, assuming that their infernal heritage has left its mark on their personality and morality, not just their appearance. Shopkeepers keep a close eye on their goods when tieflings enter their stores, the town watch might follow a tiefling around for a while, and demagogues blame tieflings for strange happenings. The reality, though, is that a tiefling's bloodline doesn't affect his or her personality to any great degree. Years of dealing with mistrust does leave its mark on most tieflings, and they respond to it in different ways. Some choose to live up to the wicked stereotype, but others are virtuous. Most are simply very aware of how people respond to them. After dealing with this mistrust throughout youth. a tiefling often develops the ability to overcome prejudice through charm or intimidation.",
  },
  {:racial_trait_id => 81,
   :description => "The tiefling are uncommon. They don't exist in every world of D&D, and even where they are found. They are less widespread than dwarves, elves, halfings, and humans.",
  },
  {:racial_trait_id => 81,
   :description => "In the cosmopolitan cities of the D&D multiverse, most people hardly look twice at members of even the most exotic races. But the small towns and villages that dot the countryside are different. The common folk aren't accustomed to seeing members of these races, and they react accordingly.",
  },
  {:racial_trait_id => 81,
   :description => "Haif-orcs are greeted with a practical caution, but tieflings are the subject of supernatural fear. The evil of their heritage is plainly visible in their features. and as far as most people are concerned, a tiefling could very well be a devil straight from the Nine Hells. People might make warding signs as a tiefling approaches, cross the street to avoid passing near, or bar shop doors before a tiefling can enter.",
  },
  {:racial_trait_id => 82,
   :description => "Tiefling names fall into three broad categories. Tieflings born into another culture typically have names reflective of that culture. Some have names derived from the Infernal language, passed down through generations, that reflect their fiendish heritage. And some younger tieflings, striving to find a place in the world, adopt a name that signifies a virtue or other concept and then try to embody that concept. For some, the chosen name is a noble quest. For others, it's a grim destiny.",
  },
  {:racial_trait_id => 83,
   :description => "With their unearthly grace and fine features, elves appear hauntingly beautiful to humans and members of many other races. They are slightly shorter than humans on average, ranging from well under 5 feet tall to just over 6 feet. They are more slender than humans, weighing only 100 to 145 pounds. Males and females are about the same height, and males are only marginally heavier than females.",
  },
  {:racial_trait_id => 83,
   :description => "Elves' coloration encompasses the normal human range and also includes skin in shades of copper, bronze, and almost bluish-white, hair of green or blue, and eyes like pools of liquid gold or silver. Elves have no facial and little body hair. They favor elegant clothing in bright colors, and they enjoy simple yet lovely jewelry,",
  },
  {:racial_trait_id => 84,
   :description => "Elves can live well over 700 years, giving them a broad perspective on events that might trouble the shorter-lived races more deeply, They are more often amused than excited, and more likely to be curious than greedy. They tend to remain aloof and unfazed by petty happenstance. When pursuing a goal, however, whether adventuring on a mission or learning a new skill or art, elves can be focused and relentless. They are slow to make friends and enemies, and even slower to forget them. They reply to petty insults with disdain and to serious insults with vengeance.",
  },
  {:racial_trait_id => 84,
   :description => "Like the branches of a young tree, elves are flexible in the face of danger. They trust in diplomacy and compromise to resolve differences before they escalate to violence. They have been known to retreat from intrusions into their woodland homes, confident that they can simply wait the invaders out. But when the need arises, elves reveal a stern martial side, demonstrating skill with sword, bow, and strategy.",
  },
  {:racial_trait_id => 85,
   :description => "Most elves dwell in small forest villages hidden among the trees. Elves hunt game, gather food, and grow vegetables, and their skill and magic allow them to support themselves without the need for clearing and plowing land. They are talented artisans, crafting finely worked clothes and art objects. Their contact with outsiders is usually limited, though a few elves make a good living by trading crafted items for metals (which they have no interest in mining).",
  },
  {:racial_trait_id => 85,
   :description => "Elves encountered outside their own lands are commonly traveling minstrels, artists, or sages. Human nobles compete for the services of elf instructors to teach swordplay or magic to their children.",
  },
  {:racial_trait_id => 86,
   :description => "Elves take up adventuring out of wanderlust. Since they are so long-lived, they can enjoy centuries of exploration and discovery. They dislike the pace of human society, which is regimented from day to day but constantly changing over decades, so they find careers that let them travel freely and set their own pace. Elves also enjoy exercising their martial prowess or gaining greater magical power, and adventuring allows them to do so. Some might join with rebels fighting against oppression, and others might become champions of moral causes.",
  },
  {:racial_trait_id => 87,
   :description => "Although they can be haughty, elves are generally gracious even to those who fall short of their high expectations- which is most non-elves. 5till, they can find good in just about anyone.",
  },
  {:racial_trait_id => 87,
   :description => "Dwarves: \"Dwarves are dull, clumsy oafs. But what they lack in humor, sophistication, and manners, they make up in valor. And I must admit, their best smiths produce art that approaches elven quality.\"",
  },
  {:racial_trait_id => 87,
   :description => "Halflings: \"Halflings are people of simple pleasures, and that is not a quality to scorn. They're good folk, they care for each other and tend their gardens, and they have proven themselves tougher than they seem when the need arises.\"",
  },
  {:racial_trait_id => 87,
   :description => "Humans: \"All that haste, their ambition and drive to accomplish something before their brief lives pass away-human endeavors seem 50 futile sometimes. But then you look at what they have accomplished, and you have to appreciate their achievements. If only they could slow down and learn some refinement.\"",
  },
  {:racial_trait_id => 88,
   :description => "Elves are considered children until they declare themselves adults, some time after the hundredth birthday, and before this period they are called by child names.",
  },
  {:racial_trait_id => 88,
   :description => "On declaring adulthood, an elf selects an adult name, although those who knew him or her as a youngster might continue to use the child name. Each elf's adult name is a unique creation, though It might reflect the names of respected individuals or other family members. Little distinction exists between male names and female names; the groupings here reflect only general tendencies. In addition, every elf bears a family name, typically a combination of other Elvish words. Some elves traveling among humans translate their family names into Common, but others retain the Elvish version.",
  },
  {:racial_trait_id => 89,
   :description => "Descended from an earlier subrace of dark-skinned elves; the drow were banished from the surface world for following the goddess Lolth down the path to evil and corruption. Now they have built their own civilization in the depths of the Underdark, patterned after the Way of Lolth. Also called dark elves, the drow have black skin that resembles polished obsidian and stark while or pale yellow hair. They commonly have very pale eyes (so pale as to be mistaken for while) in shades of lilac, silver, pink, red, and blue. They lend lo be smaller and thinner than most elves.",
  },
  {:racial_trait_id => 89,
   :description => "Drow adventurers are rare, and the race does not exist in all worlds. Check with your Dungeon Master to see if you can play a drow character.",
  },
  {:racial_trait_id => 90,
   :description => "As a forest gnome, you have a natural knack for illusion and inherent quickness and stealth. In the worlds of D&D, forest gnomes are rare and secretive. They gather in hidden communities in sylvan forests, using illusions and trickery to conceal themselves from threats or to mask their escape should they be detected. Forest gnomes tend to be friendly with other good-spirited woodland folk, and they regard elves and good fey as their most important allies. These gnomes also befriend small forest animals and rely on them for information about threats that might prowl their lands.",
  },
  {:racial_trait_id => 91,
   :description => "As a lightfoot halfling, you can easily hide from notice, even using other people as cover. You're inclined to be affable and get along well with others. In the Forgotten Realms, lightfoot halflings have spread the farthest and thus are the most common variety.",
  },
  {:racial_trait_id => 91,
   :description => "Lightfoots are more prone to wanderlust than other halflings. and often dwell alongside other races or take up a nomadic life. In the world of Greyhawk. these halflings are called hairfeet or tall fellows.",
  },
  {:racial_trait_id => 92,
   :description => "As a stout halfling, you're hardier than average and have some resistance to poison. Some say that stouts have dwarven blood. In the Forgotten Realms, these halflings are called stronghearts. and they're most common in the south.",
  },
  {:racial_trait_id => 93,
   :description => "As a high elf, you have a keen mind and a mastery of at least the basics of magic. In many of the worlds of D&D, there are two kinds of high elves. One type (which includes the gray e1ves and valley elves of Greyhawk, the Silvaoesti of Dragonlance, and the sun elves of the Forgotten Realms) is haughty and reclusive, believing themselves to be superior to non-elves and even other elves. The other type (including the high elves of Greyhawk. the Qualinesti of Dragonlance, and the moon elves of the Forgotten Realms) are more common and more friendly, and often encountered among humans and other races.",
  },
  {:racial_trait_id => 93,
   :description => "The sun elves of Faerun (also called gold elves or sunrise elves) have bronze skin and hair of copper, black, or golden blood. Their eyes are golden, silver, or black. Moon elves (also called silver elves or gray elves) are much paler, with alabaster skin sometimes tinged with blue. They often have hair of silver-while, black, or blue, but various shades of blond, brown, and red are not uncommon. Their eyes are blue or green and flecked with gold.",
  },
  {:racial_trait_id => 94,
   :description => "As a hill dwarf, you have keen senses, deep intuition, and remarkable resilience. The gold dwarves of Faerun in their mighty southern kingdom are hill dwarves, as are the exiled Neidar and the debased Klar of Krynn in the Dragonlance setting.",
  },
  {:racial_trait_id => 95,
   :description => "As a mountain dwarf, you're strong and hardy, accustomed to a difficult life in rugged terrain. You're probably on the tall side (for a dwarf), and tend toward lighter coloration, The shield dwarves of northern Faerun, as well as the ruling Hylar c1an and the noble Daewar c1an of Dragonlance, are mountain dwarves.",
  },
  {:racial_trait_id => 96,
   :description => "As a rock gnome, you have a natural inventiveness and hardiness beyond that of other gnomes. Most gnomes in the worlds of D&D are rock gnomes, including the tinker gnomes of the Dragonlance setting.",
  },
  {:racial_trait_id => 97,
   :description => "As a wood elf, you have keen senses and intuition, and your fleet feet carry you quickly and stealthily through your native forests. This category includes the wild elves (grugach) of Greyhawk and the Kagonesti of Dragonlance, as well as the races called wood elves in Greyhawk and the Forgotten Realms. In Faerun, wood elves (also called wild elves, green elves, or forest elves) are reclusive and distrusting of non-elves.",
  },
  {:racial_trait_id => 97,
   :description => "Wood elves' skin lends lo be copperish in hue, sometimes with traces of green. Their hair lends toward browns and blacks, but it is occasionally blond or copper-colored. Their eyes are green, brown, or hazel.",
  }
])
