Background.create([
  {:name => "Acolyte",
   :suggested_characteristics => "Acolytes are shaped by their experience in temples or other religious communities. Their study of the history and tenets of their faith and their relationships to temples, shrines, or hierarchies affect their mannerisms and ideals. Their flaws might be some hidden hypocrisy or heretical idea, or an ideal or bond taken to an extreme.",
   :language_variants => 2,
   :feature_id => 1,
   :is_public => true,
   :image_id => "",
   :user_id => 1
  },
  {:name => "Charlatan",
   :suggested_characteristics => "Charlatans are colorful characters who conceal their true selves behind the masks they construct. They reflect what people want to see, what they want to believe, and how they see the world. But their true selves are sometimes plagued by an uneasy conscience, an old enemy, or deep-seated trust issues.",
   :language_variants => 0,
   :feature_id => 2,
   :is_public => true,
   :image_id => "",
   :user_id => 1
  },
  {:name => "Criminal",
   :suggested_characteristics => "Criminals might seem like villains on the surface, and many of them are villainous to the core. But some have an abundance of endearing, if not redeeming, characteristics. There might be honor among thieves, but criminals rarely show any respect for law or authority.",
   :language_variants => 0,
   :feature_id => 3,
   :is_public => true,
   :image_id => "",
   :user_id => 1
  },
  {:name => "Entertainer",
   :suggested_characteristics => "Successful entertainers have to be able to capture and hold an audience's attention, so they tend to have flamboyant or forceful personalities. They're inclined toward the romantic and often cling to high-minded ideals about the practice of art and the appreciation of beauty.",
   :language_variants => 0,
   :feature_id => 4,
   :is_public => true,
   :image_id => "",
   :user_id => 1
  },
  {:name => "Folk Hero",
   :suggested_characteristics => "A folk hero is one of the common people, for better or for worse. Most folk heroes look on their humble origins as a virtue, not a shortcoming, and their home communities remain very important to them.",
   :language_variants => 0,
   :feature_id => 5,
   :is_public => true,
   :image_id => "",
   :user_id => 1
  },
  {:name => "Guild Artisan",
   :suggested_characteristics => "Guild artisans are among the most ordinary people in the world-until they set down their tools and take up an adventuring career. They understand the value of hard work and the importance of community, but they're vulnerable to sins of greed and covetousness.",
   :language_variants => 0,
   :feature_id => 6,
   :is_public => true,
   :image_id => "",
   :user_id => 1
  },
  {:name => "Hermit",
   :suggested_characteristics => "Some hermits are well suited to a life of seclusion, whereas others chafe against it and long for company. Whether they embrace solitude or long to escape it, the solitary life shapes their attitudes and ideals. A few are driven slightly mad by their years apart from society.",
   :language_variants => 1,
   :feature_id => 7,
   :is_public => true,
   :image_id => "",
   :user_id => 1
  },
  {:name => "Noble",
   :suggested_characteristics => "Nobles are born and raised to a very different lifestyle than most people ever experience, and their personalities reflect that upbringing. A noble title comes with a plethora of bonds-responsibilities to family, to other nobles (including the sovereign), to the people entrusted to the family's care, or even to the title itself. But this responsibility is often a good way to undermine a noble.",
   :language_variants => 1,
   :feature_id => 8,
   :is_public => true,
   :image_id => "",
   :user_id => 1
  },
  {:name => "Outlander",
   :suggested_characteristics => "Often considered rude and uncouth among civilized folk, outlanders have little respect for the niceties of life in the cities. The ties of tribe, e1an, family, and the natural world of which they are a part are the most important bonds lo most outlanders.",
   :language_variants => 1,
   :feature_id => 9,
   :is_public => true,
   :image_id => "",
   :user_id => 1
  },
  {:name => "Sage",
   :suggested_characteristics => "Sages are defined by their extensive studies, and their characteristics reflect this life of study. Devoted to scholarly pursuits, a sage values knowledge highly- sometimes in its own right, sometimes as a means toward other ideals.",
   :language_variants => 2,
   :feature_id => 10,
   :is_public => true,
   :image_id => "",
   :user_id => 1
  },
  {:name => "Sailor",
   :suggested_characteristics => "Sailors can be a rough lot, but the responsibilities of life on a ship make them generally reliable as well. Life aboard a ship shapes their outlook and forms their most important attachments.",
   :language_variants => 0,
   :feature_id => 11,
   :is_public => true,
   :image_id => "",
   :user_id => 1
  },
  {:name => "Soldier",
   :suggested_characteristics => "The horrors of war combined with the rigid discipline of military service leave their mark on all soldiers, shaping their ideals, creating strong bonds, and often leaving them scarred and vulnerable to fear, shame, and hatred.",
   :language_variants => 0,
   :feature_id => 12,
   :is_public => true,
   :image_id => "",
   :user_id => 1
  },
  {:name => "Urchin",
   :suggested_characteristics => "Urchins are shaped by lives of desperate poverty, for good and for ill. They tend to be driven either by a commitment to the people with whom they shared life 00 the street or by a burning desire to find a better life- and maybe get some payback on all the rich people who treated them badly.",
   :language_variants => 0,
   :feature_id => 13,
   :is_public => true,
   :image_id => "",
   :user_id => 1
  }
])
