Equipment.create([
  {:name => "Artisan's tools",
   :equipment_type_id => 7,
   :subtype => "",
   :weight => '',
   :cost => '',
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Alchemist's supplies",
   :equipment_type_id => 7,
   :subtype => "Artisan's tools",
   :weight => 8,
   :cost => 30,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Brewer's supplies",
   :equipment_type_id => 7,
   :subtype => "Artisan's tools",
   :weight => 9,
   :cost => 20,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Calligrapher's supplies",
   :equipment_type_id => 7,
   :subtype => "Artisan's tools",
   :weight => 5,
   :cost => 10,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Carpenter tools",
   :equipment_type_id => 7,
   :subtype => "Artisan's tools",
   :weight => 6,
   :cost => 8,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Cartographer's tools",
   :equipment_type_id => 7,
   :subtype => "",
   :weight => 6,
   :cost => 15,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Cobbler's tools",
   :equipment_type_id => 7,
   :subtype => "Artisan's tools",
   :weight => 5,
   :cost => 5,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Cook's utensils",
   :equipment_type_id => 7,
   :subtype => "Artisan's tools",
   :weight => 8,
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Glassblower's tools",
   :equipment_type_id => 7,
   :subtype => "Artisan's tools",
   :weight => 5,
   :cost => 30,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Jeweler's tools",
   :equipment_type_id => 7,
   :subtype => "Artisan's tools",
   :weight => 2,
   :cost => 25,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Leatherworker's tools",
   :equipment_type_id => 7,
   :subtype => "Artisan's tools",
   :weight => 5,
   :cost => 5,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Mason's tools",
   :equipment_type_id => 7,
   :subtype => "Artisan's tools",
   :weight => 8,
   :cost => 10,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Painter's supplies",
   :equipment_type_id => 7,
   :subtype => "Artisan's tools",
   :weight => 5,
   :cost => 10,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Potter's tools",
   :equipment_type_id => 7,
   :subtype => "Artisan's tools",
   :weight => 3,
   :cost => 10,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Smith's tools",
   :equipment_type_id => 7,
   :subtype => "Artisan's tools",
   :weight => 8,
   :cost => 20,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Tinker's tools",
   :equipment_type_id => 7,
   :subtype => "Artisan's tools",
   :weight => 10,
   :cost => 50,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Weaver's tools",
   :equipment_type_id => 7,
   :subtype => "Artisan's tools",
   :weight => 5,
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Woodcarver's tools",
   :equipment_type_id => 7,
   :subtype => "Artisan's tools",
   :weight => 5,
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Disguise kit",
   :equipment_type_id => 7,
   :subtype => "",
   :weight => 2,
   :cost => 15,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Forgery kit",
   :equipment_type_id => 7,
   :subtype => "",
   :weight => 5,
   :cost => 15,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Gaming set",
   :equipment_type_id => 7,
   :subtype => "",
   :weight => '',
   :cost => '',
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Dice set",
   :equipment_type_id => 7,
   :subtype => "Gaming set",
   :weight => 0,
   :cost => 1,
   :currency => "sp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Dragonchess set",
   :equipment_type_id => 7,
   :subtype => "Gaming set",
   :weight => 0.5,
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Playing card set",
   :equipment_type_id => 7,
   :subtype => "Gaming set",
   :weight => 0,
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Three-Dragon Ante set",
   :equipment_type_id => 7,
   :subtype => "Gaming set",
   :weight => 0,
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Herbalism kit",
   :equipment_type_id => 7,
   :subtype => "",
   :weight => 3,
   :cost => 5,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Musical instrument",
   :equipment_type_id => 7,
   :subtype => "",
   :weight => '',
   :cost => '',
   :currency => "",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Bagpipes",
   :equipment_type_id => 7,
   :subtype => "Musical instrument",
   :weight => 6,
   :cost => 30,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Drums",
   :equipment_type_id => 7,
   :subtype => "Musical instrument",
   :weight => 3,
   :cost => 6,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Dulcimer",
   :equipment_type_id => 7,
   :subtype => "Musical instrument",
   :weight => 10,
   :cost => 25,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Flute",
   :equipment_type_id => 7,
   :subtype => "Musical instrument",
   :weight => 1,
   :cost => 2,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Lute",
   :equipment_type_id => 7,
   :subtype => "Musical instrument",
   :weight => 2,
   :cost => 35,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Lyre",
   :equipment_type_id => 7,
   :subtype => "Musical instrument",
   :weight => 2,
   :cost => 30,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Horn",
   :equipment_type_id => 7,
   :subtype => "Musical instrument",
   :weight => 2,
   :cost => 3,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Pan flute",
   :equipment_type_id => 7,
   :subtype => "Musical instrument",
   :weight => 2,
   :cost => 12,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Shawm",
   :equipment_type_id => 7,
   :subtype => "Musical instrument",
   :weight => 1,
   :cost => 2,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Viol",
   :equipment_type_id => 7,
   :subtype => "Musical instrument",
   :weight => 1,
   :cost => 30,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Navigator's tools",
   :equipment_type_id => 7,
   :subtype => "",
   :weight => 2,
   :cost => 25,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Poisoner's kit",
   :equipment_type_id => 7,
   :subtype => "",
   :weight => 2,
   :cost => 50,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Thieves' tools",
   :equipment_type_id => 7,
   :subtype => "",
   :weight => 1,
   :cost => 25,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  }
])
