Equipment.create([
  {:name => "Artisan's tools",
   :equipment_type_id => 7,
   :subtype => "",
   :weight => '',
   :cost => '',
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Alchemist's supplies",
   :equipment_type_id => 7,
   :subtype => "Artisan's tools",
   :weight => 8,
   :cost => 30,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Brewer's supplies",
   :equipment_type_id => 7,
   :subtype => "Artisan's tools",
   :weight => 9,
   :cost => 20,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Calligrapher's supplies",
   :equipment_type_id => 7,
   :subtype => "Artisan's tools",
   :weight => 5,
   :cost => 10,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Carpenter tools",
   :equipment_type_id => 7,
   :subtype => "Artisan's tools",
   :weight => 6,
   :cost => 8,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Cartographer's tools",
   :equipment_type_id => 7,
   :subtype => "",
   :weight => 6,
   :cost => 15,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Cobbler's tools",
   :equipment_type_id => 7,
   :subtype => "Artisan's tools",
   :weight => 5,
   :cost => 5,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Cook's utensils",
   :equipment_type_id => 7,
   :subtype => "Artisan's tools",
   :weight => 8,
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Glassblower's tools",
   :equipment_type_id => 7,
   :subtype => "Artisan's tools",
   :weight => 5,
   :cost => 30,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Jeweler's tools",
   :equipment_type_id => 7,
   :subtype => "Artisan's tools",
   :weight => 2,
   :cost => 25,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Leatherworker's tools",
   :equipment_type_id => 7,
   :subtype => "Artisan's tools",
   :weight => 5,
   :cost => 5,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Mason's tools",
   :equipment_type_id => 7,
   :subtype => "Artisan's tools",
   :weight => 8,
   :cost => 10,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Painter's supplies",
   :equipment_type_id => 7,
   :subtype => "Artisan's tools",
   :weight => 5,
   :cost => 10,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Potter's tools",
   :equipment_type_id => 7,
   :subtype => "Artisan's tools",
   :weight => 3,
   :cost => 10,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Smith's tools",
   :equipment_type_id => 7,
   :subtype => "Artisan's tools",
   :weight => 8,
   :cost => 20,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Tinker's tools",
   :equipment_type_id => 7,
   :subtype => "Artisan's tools",
   :weight => 10,
   :cost => 50,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Weaver's tools",
   :equipment_type_id => 7,
   :subtype => "Artisan's tools",
   :weight => 5,
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Woodcarver's tools",
   :equipment_type_id => 7,
   :subtype => "Artisan's tools",
   :weight => 5,
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Disguise kit",
   :equipment_type_id => 7,
   :subtype => "",
   :weight => 2,
   :cost => 15,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Forgery kit",
   :equipment_type_id => 7,
   :subtype => "",
   :weight => 5,
   :cost => 15,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Gaming set",
   :equipment_type_id => 7,
   :subtype => "",
   :weight => '',
   :cost => '',
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Dice set",
   :equipment_type_id => 7,
   :subtype => "Gaming set",
   :weight => 0,
   :cost => 1,
   :currency => "sp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Dragonchess set",
   :equipment_type_id => 7,
   :subtype => "Gaming set",
   :weight => 0.5,
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Playing card set",
   :equipment_type_id => 7,
   :subtype => "Gaming set",
   :weight => 0,
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Three-Dragon Ante set",
   :equipment_type_id => 7,
   :subtype => "Gaming set",
   :weight => 0,
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Herbalism kit",
   :equipment_type_id => 7,
   :subtype => "",
   :weight => 3,
   :cost => 5,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Musical instrument",
   :equipment_type_id => 7,
   :subtype => "",
   :weight => '',
   :cost => '',
   :currency => "",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Bagpipes",
   :equipment_type_id => 7,
   :subtype => "Musical instrument",
   :weight => 6,
   :cost => 30,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Drums",
   :equipment_type_id => 7,
   :subtype => "Musical instrument",
   :weight => 3,
   :cost => 6,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Dulcimer",
   :equipment_type_id => 7,
   :subtype => "Musical instrument",
   :weight => 10,
   :cost => 25,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Flute",
   :equipment_type_id => 7,
   :subtype => "Musical instrument",
   :weight => 1,
   :cost => 2,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Lute",
   :equipment_type_id => 7,
   :subtype => "Musical instrument",
   :weight => 2,
   :cost => 35,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Lyre",
   :equipment_type_id => 7,
   :subtype => "Musical instrument",
   :weight => 2,
   :cost => 30,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Horn",
   :equipment_type_id => 7,
   :subtype => "Musical instrument",
   :weight => 2,
   :cost => 3,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Pan flute",
   :equipment_type_id => 7,
   :subtype => "Musical instrument",
   :weight => 2,
   :cost => 12,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Shawm",
   :equipment_type_id => 7,
   :subtype => "Musical instrument",
   :weight => 1,
   :cost => 2,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Viol",
   :equipment_type_id => 7,
   :subtype => "Musical instrument",
   :weight => 1,
   :cost => 30,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Navigator's tools",
   :equipment_type_id => 7,
   :subtype => "",
   :weight => 2,
   :cost => 25,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Poisoner's kit",
   :equipment_type_id => 7,
   :subtype => "",
   :weight => 2,
   :cost => 50,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Thieves' tools",
   :equipment_type_id => 7,
   :subtype => "",
   :weight => 1,
   :cost => 25,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Coin",
   :equipment_type_id => 9,
   :subtype => "",
   :weight => '',
   :cost => '',
   :currency => "",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Copper",
   :equipment_type_id => 9,
   :subtype => "Coin",
   :weight => '',
   :cost => '',
   :currency => "",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Silver",
   :equipment_type_id => 9,
   :subtype => "Coin",
   :weight => '',
   :cost => '',
   :currency => "",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Electrum",
   :equipment_type_id => 9,
   :subtype => "Coin",
   :weight => '',
   :cost => '',
   :currency => "",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Gold",
   :equipment_type_id => 9,
   :subtype => "Coin",
   :weight => '',
   :cost => '',
   :currency => "",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Platinum",
   :equipment_type_id => 9,
   :subtype => "Coin",
   :weight => '',
   :cost => '',
   :currency => "",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Light Armor",
   :equipment_type_id => 3,
   :subtype => "",
   :weight => '',
   :cost => '',
   :currency => "",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Medium Armor",
   :equipment_type_id => 3,
   :subtype => "",
   :weight => '',
   :cost => '',
   :currency => "",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Heavy Armor",
   :equipment_type_id => 3,
   :subtype => "",
   :weight => '',
   :cost => '',
   :currency => "",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Padded Armor",
   :equipment_type_id => 3,
   :subtype => "Light Armor",
   :weight => 8,
   :cost => 5,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Leather Armor",
   :equipment_type_id => 3,
   :subtype => "Light Armor",
   :weight => 10,
   :cost => 10,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Studded Leather Armor",
   :equipment_type_id => 3,
   :subtype => "Light Armor",
   :weight => 13,
   :cost => 45,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Hide Armor",
   :equipment_type_id => 3,
   :subtype => "Medium Armor",
   :weight => 12,
   :cost => 10,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Chain Shirt",
   :equipment_type_id => 3,
   :subtype => "Medium Armor",
   :weight => 20,
   :cost => 50,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Scale Mail",
   :equipment_type_id => 3,
   :subtype => "Medium Armor",
   :weight => 45,
   :cost => 50,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Breastplate",
   :equipment_type_id => 3,
   :subtype => "Medium Armor",
   :weight => 20,
   :cost => 400,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Half Plate",
   :equipment_type_id => 3,
   :subtype => "Medium Armor",
   :weight => 40,
   :cost => 750,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Ring Mail",
   :equipment_type_id => 3,
   :subtype => "Heavy Armor",
   :weight => 40,
   :cost => 30,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Chain Mail",
   :equipment_type_id => 3,
   :subtype => "Heavy Armor",
   :weight => 55,
   :cost => 75,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Splint Armor",
   :equipment_type_id => 3,
   :subtype => "Heavy Armor",
   :weight => 60,
   :cost => 200,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Plate Armor",
   :equipment_type_id => 3,
   :subtype => "Heavy Armor",
   :weight => 65,
   :cost => 1500,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Shields",
   :equipment_type_id => 6,
   :subtype => "",
   :weight => '',
   :cost => '',
   :currency => "",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Shield",
   :equipment_type_id => 6,
   :subtype => "Shields",
   :weight => 6,
   :cost => 10,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Club",
   :equipment_type_id => 10,
   :subtype => "Simple",
   :weight => 2,
   :cost => 1,
   :currency => "sp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Dagger",
   :equipment_type_id => 10,
   :subtype => "Simple",
   :weight => 1,
   :cost => 2,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Greatclub",
   :equipment_type_id => 10,
   :subtype => "Simple",
   :weight => 10,
   :cost => 2,
   :currency => "sp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Handaxe",
   :equipment_type_id => 10,
   :subtype => "Simple",
   :weight => 2,
   :cost => 5,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Javelin",
   :equipment_type_id => 10,
   :subtype => "Simple",
   :weight => 2,
   :cost => 5,
   :currency => "sp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Light hammer",
   :equipment_type_id => 10,
   :subtype => "Simple",
   :weight => 2,
   :cost => 2,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Mace",
   :equipment_type_id => 10,
   :subtype => "Simple",
   :weight => 4,
   :cost => 5,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Quarterstaff",
   :equipment_type_id => 10,
   :subtype => "Simple",
   :weight => 4,
   :cost => 2,
   :currency => "sp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Sickle",
   :equipment_type_id => 10,
   :subtype => "Simple",
   :weight => 2,
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Spear",
   :equipment_type_id => 10,
   :subtype => "Simple",
   :weight => 3,
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Unarmed strike",
   :equipment_type_id => 10,
   :subtype => "Simple",
   :weight => '',
   :cost => '',
   :currency => "",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Crossbow, light",
   :equipment_type_id => 11,
   :subtype => "Simple",
   :weight => 5,
   :cost => 25,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Dart",
   :equipment_type_id => 11,
   :subtype => "Simple",
   :weight => 0.25,
   :cost => 5,
   :currency => "cp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Shortbow",
   :equipment_type_id => 11,
   :subtype => "Simple",
   :weight => 2,
   :cost => 25,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Sling",
   :equipment_type_id => 11,
   :subtype => "Simple",
   :weight => 0,
   :cost => 1,
   :currency => "sp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Battleaxe",
   :equipment_type_id => 10,
   :subtype => "Martial",
   :weight => 4,
   :cost => 10,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Flail",
   :equipment_type_id => 10,
   :subtype => "Martial",
   :weight => 2,
   :cost => 10,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Glaive",
   :equipment_type_id => 10,
   :subtype => "Martial",
   :weight => 6,
   :cost => 20,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Greataxe",
   :equipment_type_id => 10,
   :subtype => "Martial",
   :weight => 7,
   :cost => 30,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Greatsword",
   :equipment_type_id => 10,
   :subtype => "Martial",
   :weight => 6,
   :cost => 50,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Halberd",
   :equipment_type_id => 10,
   :subtype => "Martial",
   :weight => 6,
   :cost => 20,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Lance",
   :equipment_type_id => 10,
   :subtype => "Martial",
   :weight => 6,
   :cost => 10,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Longsword",
   :equipment_type_id => 10,
   :subtype => "Martial",
   :weight => 3,
   :cost => 15,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Maul",
   :equipment_type_id => 10,
   :subtype => "Martial",
   :weight => 10,
   :cost => 10,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Morningstar",
   :equipment_type_id => 10,
   :subtype => "Martial",
   :weight => 4,
   :cost => 15,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Pike",
   :equipment_type_id => 10,
   :subtype => "Martial",
   :weight => 18,
   :cost => 5,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Rapier",
   :equipment_type_id => 10,
   :subtype => "Martial",
   :weight => 2,
   :cost => 25,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Scimitar",
   :equipment_type_id => 10,
   :subtype => "Martial",
   :weight => 3,
   :cost => 25,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Shortsword",
   :equipment_type_id => 10,
   :subtype => "Martial",
   :weight => 2,
   :cost => 10,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Trident",
   :equipment_type_id => 10,
   :subtype => "Martial",
   :weight => 4,
   :cost => 5,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "War pick",
   :equipment_type_id => 10,
   :subtype => "Martial",
   :weight => 2,
   :cost => 15,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Whip",
   :equipment_type_id => 10,
   :subtype => "Martial",
   :weight => 3,
   :cost => 2,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Blowgun",
   :equipment_type_id => 11,
   :subtype => "Martial",
   :weight => 1,
   :cost => 10,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Crossbow, hand",
   :equipment_type_id => 11,
   :subtype => "Martial",
   :weight => 3,
   :cost => 75,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Crossbow, heavy",
   :equipment_type_id => 11,
   :subtype => "Martial",
   :weight => 18,
   :cost => 50,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Longbow",
   :equipment_type_id => 11,
   :subtype => "Martial",
   :weight => 2,
   :cost => 50,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Net",
   :equipment_type_id => 11,
   :subtype => "Martial",
   :weight => 3,
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Abacus",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 2,
   :cost => 2,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Acid (vial)",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 1,
   :cost => 25,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Alchemist's fire (flask)",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 1,
   :cost => 50,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Arrows (20)",
   :equipment_type_id => 2,
   :subtype => "",
   :weight => 1,
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Blowgun needles (50)",
   :equipment_type_id => 2,
   :subtype => "",
   :weight => 1,
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Crossbow bolts (20)",
   :equipment_type_id => 2,
   :subtype => "",
   :weight => 1.5,
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Sling bullets (20)",
   :equipment_type_id => 2,
   :subtype => "",
   :weight => 1.5,
   :cost => 4,
   :currency => "cp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Antitoxin (vial)",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => '',
   :cost => 50,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Crystal",
   :equipment_type_id => 1,
   :subtype => "Arcane focus",
   :weight => 1,
   :cost => 10,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Orb",
   :equipment_type_id => 1,
   :subtype => "Arcane focus",
   :weight => 3,
   :cost => 20,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Rod",
   :equipment_type_id => 1,
   :subtype => "Arcane focus",
   :weight => 2,
   :cost => 10,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Staff",
   :equipment_type_id => 1,
   :subtype => "Arcane focus",
   :weight => 4,
   :cost => 5,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Wand",
   :equipment_type_id => 1,
   :subtype => "Arcane focus",
   :weight => 1,
   :cost => 10,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Backpack",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 5,
   :cost => 2,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Ball bearings (bag of 1000)",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 2,
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Barrel",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 70,
   :cost => 2,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Basket",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 2,
   :cost => 4,
   :currency => "sp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Bedroll",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 7,
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Bell",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => '',
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Blanket",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 3,
   :cost => 5,
   :currency => "sp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Block and tackle",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 5,
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Book",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 5,
   :cost => 25,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Bottle, glass",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 2,
   :cost => 2,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Bucket",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 2,
   :cost => 5,
   :currency => "cp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Caltrops (bag of 20)",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 2,
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Candle",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => '',
   :cost => 1,
   :currency => "cp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Case, crossbow bolt",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 1,
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Case, map or scroll",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 1,
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Chain (10 feet)",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 10,
   :cost => 5,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Chalk (1 piece)",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => '',
   :cost => 1,
   :currency => "cp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Chest",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 25,
   :cost => 5,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Climber's kit",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 12,
   :cost => 25,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Clothes, common",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 3,
   :cost => 5,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Clothes, costume",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 4,
   :cost => 5,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Clothes, fine",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 6,
   :cost => 15,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Clothes, traveler's",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 4,
   :cost => 2,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Component pouch",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 2,
   :cost => 25,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Crowbar",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 5,
   :cost => 2,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Sprig of mistletoe",
   :equipment_type_id => 1,
   :subtype => "Druidic focus",
   :weight => '',
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Totem",
   :equipment_type_id => 1,
   :subtype => "Druidic focus",
   :weight => '',
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Wooden staff",
   :equipment_type_id => 1,
   :subtype => "Druidic focus",
   :weight => 4,
   :cost => 5,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Yew wand",
   :equipment_type_id => 1,
   :subtype => "Druidic focus",
   :weight => 1,
   :cost => 10,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Fishing tackle",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 4,
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Flask or tankard",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 1,
   :cost => 2,
   :currency => "cp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Grappling hook",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 4,
   :cost => 2,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Hammer",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 3,
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Hammer, sledge",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 10,
   :cost => 2,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Healer's kit",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 3,
   :cost => 5,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Amulet",
   :equipment_type_id => 1,
   :subtype => "Holy symbol",
   :weight => 1,
   :cost => 5,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Emblem",
   :equipment_type_id => 1,
   :subtype => "Holy symbol",
   :weight => '',
   :cost => 5,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Reliquary",
   :equipment_type_id => 1,
   :subtype => "Holy symbol",
   :weight => 2,
   :cost => 5,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Holy water (flask)",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 1,
   :cost => 25,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Hourglass",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 1,
   :cost => 25,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Hunting trap",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 25,
   :cost => 5,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Ink (1 ounce bottle)",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => '',
   :cost => 10,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Ink pen",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => '',
   :cost => 2,
   :currency => "cp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Jug or pitcher",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 4,
   :cost => 2,
   :currency => "cp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Ladder (10 foot)",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 25,
   :cost => 1,
   :currency => "sp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Lamp",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 1,
   :cost => 5,
   :currency => "sp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Lantern, bullseye",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 2,
   :cost => 10,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Lantern, hooded",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 2,
   :cost => 5,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Lock",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 1,
   :cost => 10,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Magnifying glass",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => '',
   :cost => 100,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Manacles",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 6,
   :cost => 2,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Mess kit",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 1,
   :cost => 2,
   :currency => "sp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Mirror, steel",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 0.5,
   :cost => 5,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Oil (flask)",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 1,
   :cost => 1,
   :currency => "sp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Paper (one sheet)",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => '',
   :cost => 2,
   :currency => "sp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Parchment (one sheet)",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => '',
   :cost => 1,
   :currency => "sp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Perfume (vial)",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => '',
   :cost => 5,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Pick, miner's",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 10,
   :cost => 2,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Piton",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 0.25,
   :cost => 5,
   :currency => "cp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Poison, basic (vial)",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => '',
   :cost => 100,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Pole (10 foot)",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 7,
   :cost => 5,
   :currency => "cp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Pot, iron",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 10,
   :cost => 2,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Potion of healing",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 0.5,
   :cost => 50,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Pouch",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 1,
   :cost => 5,
   :currency => "sp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Quiver",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 1,
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Ram, portable",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 35,
   :cost => 4,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Rations (1 day)",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 2,
   :cost => 5,
   :currency => "sp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Robes",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 4,
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Rope, hempen (50 feet)",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 10,
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Rope, silk (50 feet)",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 5,
   :cost => 10,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Sack",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 0.5,
   :cost => 1,
   :currency => "cp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Scale, merchant's",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 3,
   :cost => 5,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Sealing wax",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => '',
   :cost => 5,
   :currency => "sp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Shovel",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 5,
   :cost => 2,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Signal whistle",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => '',
   :cost => 5,
   :currency => "cp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Signet ring",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => '',
   :cost => 5,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Soap",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => '',
   :cost => 2,
   :currency => "cp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Spellbook",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 3,
   :cost => 50,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Spikes, iron (10)",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 5,
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Spyglass",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 1,
   :cost => 1000,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Tent, two-person",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 20,
   :cost => 2,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Tinderbox",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 1,
   :cost => 5,
   :currency => "sp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Torch",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 1,
   :cost => 1,
   :currency => "cp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Vial",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => '',
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Waterskin",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 5,
   :cost => 2,
   :currency => "sp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Whetstone",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 1,
   :cost => 1,
   :currency => "cp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  }
])
