Equipment.create([
  {:name => "Artisan's tools",
   :equipment_type_id => 7,
   :subtype => "",
   :weight => '',
   :cost => '',
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Alchemist's supplies",
   :equipment_type_id => 7,
   :subtype => "Artisan's tools",
   :weight => 8,
   :cost => 30,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Brewer's supplies",
   :equipment_type_id => 7,
   :subtype => "Artisan's tools",
   :weight => 9,
   :cost => 20,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Calligrapher's supplies",
   :equipment_type_id => 7,
   :subtype => "Artisan's tools",
   :weight => 5,
   :cost => 10,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Carpenter tools",
   :equipment_type_id => 7,
   :subtype => "Artisan's tools",
   :weight => 6,
   :cost => 8,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Cartographer's tools",
   :equipment_type_id => 7,
   :subtype => "",
   :weight => 6,
   :cost => 15,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Cobbler's tools",
   :equipment_type_id => 7,
   :subtype => "Artisan's tools",
   :weight => 5,
   :cost => 5,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Cook's utensils",
   :equipment_type_id => 7,
   :subtype => "Artisan's tools",
   :weight => 8,
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Glassblower's tools",
   :equipment_type_id => 7,
   :subtype => "Artisan's tools",
   :weight => 5,
   :cost => 30,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Jeweler's tools",
   :equipment_type_id => 7,
   :subtype => "Artisan's tools",
   :weight => 2,
   :cost => 25,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Leatherworker's tools",
   :equipment_type_id => 7,
   :subtype => "Artisan's tools",
   :weight => 5,
   :cost => 5,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Mason's tools",
   :equipment_type_id => 7,
   :subtype => "Artisan's tools",
   :weight => 8,
   :cost => 10,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Painter's supplies",
   :equipment_type_id => 7,
   :subtype => "Artisan's tools",
   :weight => 5,
   :cost => 10,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Potter's tools",
   :equipment_type_id => 7,
   :subtype => "Artisan's tools",
   :weight => 3,
   :cost => 10,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Smith's tools",
   :equipment_type_id => 7,
   :subtype => "Artisan's tools",
   :weight => 8,
   :cost => 20,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Tinker's tools",
   :equipment_type_id => 7,
   :subtype => "Artisan's tools",
   :weight => 10,
   :cost => 50,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Weaver's tools",
   :equipment_type_id => 7,
   :subtype => "Artisan's tools",
   :weight => 5,
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Woodcarver's tools",
   :equipment_type_id => 7,
   :subtype => "Artisan's tools",
   :weight => 5,
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Disguise kit",
   :equipment_type_id => 7,
   :subtype => "",
   :weight => 2,
   :cost => 15,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Forgery kit",
   :equipment_type_id => 7,
   :subtype => "",
   :weight => 5,
   :cost => 15,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Gaming set",
   :equipment_type_id => 7,
   :subtype => "",
   :weight => '',
   :cost => '',
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Dice set",
   :equipment_type_id => 7,
   :subtype => "Gaming set",
   :weight => 0,
   :cost => 1,
   :currency => "sp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Dragonchess set",
   :equipment_type_id => 7,
   :subtype => "Gaming set",
   :weight => 0.5,
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Playing card set",
   :equipment_type_id => 7,
   :subtype => "Gaming set",
   :weight => 0,
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Three-Dragon Ante set",
   :equipment_type_id => 7,
   :subtype => "Gaming set",
   :weight => 0,
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Herbalism kit",
   :equipment_type_id => 7,
   :subtype => "",
   :weight => 3,
   :cost => 5,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Musical instrument",
   :equipment_type_id => 7,
   :subtype => "",
   :weight => '',
   :cost => '',
   :currency => "",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Bagpipes",
   :equipment_type_id => 7,
   :subtype => "Musical instrument",
   :weight => 6,
   :cost => 30,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Drums",
   :equipment_type_id => 7,
   :subtype => "Musical instrument",
   :weight => 3,
   :cost => 6,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Dulcimer",
   :equipment_type_id => 7,
   :subtype => "Musical instrument",
   :weight => 10,
   :cost => 25,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Flute",
   :equipment_type_id => 7,
   :subtype => "Musical instrument",
   :weight => 1,
   :cost => 2,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Lute",
   :equipment_type_id => 7,
   :subtype => "Musical instrument",
   :weight => 2,
   :cost => 35,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Lyre",
   :equipment_type_id => 7,
   :subtype => "Musical instrument",
   :weight => 2,
   :cost => 30,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Horn",
   :equipment_type_id => 7,
   :subtype => "Musical instrument",
   :weight => 2,
   :cost => 3,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Pan flute",
   :equipment_type_id => 7,
   :subtype => "Musical instrument",
   :weight => 2,
   :cost => 12,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Shawm",
   :equipment_type_id => 7,
   :subtype => "Musical instrument",
   :weight => 1,
   :cost => 2,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Viol",
   :equipment_type_id => 7,
   :subtype => "Musical instrument",
   :weight => 1,
   :cost => 30,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Navigator's tools",
   :equipment_type_id => 7,
   :subtype => "",
   :weight => 2,
   :cost => 25,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Poisoner's kit",
   :equipment_type_id => 7,
   :subtype => "",
   :weight => 2,
   :cost => 50,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Thieves' tools",
   :equipment_type_id => 7,
   :subtype => "",
   :weight => 1,
   :cost => 25,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Coin",
   :equipment_type_id => 9,
   :subtype => "",
   :weight => '',
   :cost => '',
   :currency => "",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Copper",
   :equipment_type_id => 9,
   :subtype => "Coin",
   :weight => '',
   :cost => '',
   :currency => "",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Silver",
   :equipment_type_id => 9,
   :subtype => "Coin",
   :weight => '',
   :cost => '',
   :currency => "",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Electrum",
   :equipment_type_id => 9,
   :subtype => "Coin",
   :weight => '',
   :cost => '',
   :currency => "",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Gold",
   :equipment_type_id => 9,
   :subtype => "Coin",
   :weight => '',
   :cost => '',
   :currency => "",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Platinum",
   :equipment_type_id => 9,
   :subtype => "Coin",
   :weight => '',
   :cost => '',
   :currency => "",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Light Armor",
   :equipment_type_id => 3,
   :subtype => "",
   :weight => '',
   :cost => '',
   :currency => "",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Medium Armor",
   :equipment_type_id => 3,
   :subtype => "",
   :weight => '',
   :cost => '',
   :currency => "",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Heavy Armor",
   :equipment_type_id => 3,
   :subtype => "",
   :weight => '',
   :cost => '',
   :currency => "",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Padded Armor",
   :equipment_type_id => 3,
   :subtype => "Light Armor",
   :weight => 8,
   :cost => 5,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Leather Armor",
   :equipment_type_id => 3,
   :subtype => "Light Armor",
   :weight => 10,
   :cost => 10,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Studded Leather Armor",
   :equipment_type_id => 3,
   :subtype => "Light Armor",
   :weight => 13,
   :cost => 45,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Hide Armor",
   :equipment_type_id => 3,
   :subtype => "Medium Armor",
   :weight => 12,
   :cost => 10,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Chain Shirt",
   :equipment_type_id => 3,
   :subtype => "Medium Armor",
   :weight => 20,
   :cost => 50,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Scale Mail",
   :equipment_type_id => 3,
   :subtype => "Medium Armor",
   :weight => 45,
   :cost => 50,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Breastplate",
   :equipment_type_id => 3,
   :subtype => "Medium Armor",
   :weight => 20,
   :cost => 400,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Half Plate",
   :equipment_type_id => 3,
   :subtype => "Medium Armor",
   :weight => 40,
   :cost => 750,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Ring Mail",
   :equipment_type_id => 3,
   :subtype => "Heavy Armor",
   :weight => 40,
   :cost => 30,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Chain Mail",
   :equipment_type_id => 3,
   :subtype => "Heavy Armor",
   :weight => 55,
   :cost => 75,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Splint Armor",
   :equipment_type_id => 3,
   :subtype => "Heavy Armor",
   :weight => 60,
   :cost => 200,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Plate Armor",
   :equipment_type_id => 3,
   :subtype => "Heavy Armor",
   :weight => 65,
   :cost => 1500,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Shields",
   :equipment_type_id => 6,
   :subtype => "",
   :weight => '',
   :cost => '',
   :currency => "",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Shield",
   :equipment_type_id => 6,
   :subtype => "Shields",
   :weight => 6,
   :cost => 10,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Club",
   :equipment_type_id => 10,
   :subtype => "Simple",
   :weight => 2,
   :cost => 1,
   :currency => "sp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Dagger",
   :equipment_type_id => 10,
   :subtype => "Simple",
   :weight => 1,
   :cost => 2,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Greatclub",
   :equipment_type_id => 10,
   :subtype => "Simple",
   :weight => 10,
   :cost => 2,
   :currency => "sp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Handaxe",
   :equipment_type_id => 10,
   :subtype => "Simple",
   :weight => 2,
   :cost => 5,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Javelin",
   :equipment_type_id => 10,
   :subtype => "Simple",
   :weight => 2,
   :cost => 5,
   :currency => "sp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Light hammer",
   :equipment_type_id => 10,
   :subtype => "Simple",
   :weight => 2,
   :cost => 2,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Mace",
   :equipment_type_id => 10,
   :subtype => "Simple",
   :weight => 4,
   :cost => 5,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Quarterstaff",
   :equipment_type_id => 10,
   :subtype => "Simple",
   :weight => 4,
   :cost => 2,
   :currency => "sp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Sickle",
   :equipment_type_id => 10,
   :subtype => "Simple",
   :weight => 2,
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Spear",
   :equipment_type_id => 10,
   :subtype => "Simple",
   :weight => 3,
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Unarmed strike",
   :equipment_type_id => 10,
   :subtype => "Simple",
   :weight => '',
   :cost => '',
   :currency => "",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Crossbow, light",
   :equipment_type_id => 11,
   :subtype => "Simple",
   :weight => 5,
   :cost => 25,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Dart",
   :equipment_type_id => 11,
   :subtype => "Simple",
   :weight => 0.25,
   :cost => 5,
   :currency => "cp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Shortbow",
   :equipment_type_id => 11,
   :subtype => "Simple",
   :weight => 2,
   :cost => 25,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Sling",
   :equipment_type_id => 11,
   :subtype => "Simple",
   :weight => 0,
   :cost => 1,
   :currency => "sp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Battleaxe",
   :equipment_type_id => 10,
   :subtype => "Martial",
   :weight => 4,
   :cost => 10,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Flail",
   :equipment_type_id => 10,
   :subtype => "Martial",
   :weight => 2,
   :cost => 10,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Glaive",
   :equipment_type_id => 10,
   :subtype => "Martial",
   :weight => 6,
   :cost => 20,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Greataxe",
   :equipment_type_id => 10,
   :subtype => "Martial",
   :weight => 7,
   :cost => 30,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Greatsword",
   :equipment_type_id => 10,
   :subtype => "Martial",
   :weight => 6,
   :cost => 50,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Halberd",
   :equipment_type_id => 10,
   :subtype => "Martial",
   :weight => 6,
   :cost => 20,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Lance",
   :equipment_type_id => 10,
   :subtype => "Martial",
   :weight => 6,
   :cost => 10,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Longsword",
   :equipment_type_id => 10,
   :subtype => "Martial",
   :weight => 3,
   :cost => 15,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Maul",
   :equipment_type_id => 10,
   :subtype => "Martial",
   :weight => 10,
   :cost => 10,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Morningstar",
   :equipment_type_id => 10,
   :subtype => "Martial",
   :weight => 4,
   :cost => 15,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Pike",
   :equipment_type_id => 10,
   :subtype => "Martial",
   :weight => 18,
   :cost => 5,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Rapier",
   :equipment_type_id => 10,
   :subtype => "Martial",
   :weight => 2,
   :cost => 25,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Scimitar",
   :equipment_type_id => 10,
   :subtype => "Martial",
   :weight => 3,
   :cost => 25,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Shortsword",
   :equipment_type_id => 10,
   :subtype => "Martial",
   :weight => 2,
   :cost => 10,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Trident",
   :equipment_type_id => 10,
   :subtype => "Martial",
   :weight => 4,
   :cost => 5,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "War pick",
   :equipment_type_id => 10,
   :subtype => "Martial",
   :weight => 2,
   :cost => 15,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Whip",
   :equipment_type_id => 10,
   :subtype => "Martial",
   :weight => 3,
   :cost => 2,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Blowgun",
   :equipment_type_id => 11,
   :subtype => "Martial",
   :weight => 1,
   :cost => 10,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Crossbow, hand",
   :equipment_type_id => 11,
   :subtype => "Martial",
   :weight => 3,
   :cost => 75,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Crossbow, heavy",
   :equipment_type_id => 11,
   :subtype => "Martial",
   :weight => 18,
   :cost => 50,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Longbow",
   :equipment_type_id => 11,
   :subtype => "Martial",
   :weight => 2,
   :cost => 50,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Net",
   :equipment_type_id => 11,
   :subtype => "Martial",
   :weight => 3,
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Abacus",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 2,
   :cost => 2,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Acid (vial)",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 1,
   :cost => 25,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Alchemist's fire (flask)",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 1,
   :cost => 50,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Arrows (20)",
   :equipment_type_id => 2,
   :subtype => "",
   :weight => 1,
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Blowgun needles (50)",
   :equipment_type_id => 2,
   :subtype => "",
   :weight => 1,
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Crossbow bolts (20)",
   :equipment_type_id => 2,
   :subtype => "",
   :weight => 1.5,
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Sling bullets (20)",
   :equipment_type_id => 2,
   :subtype => "",
   :weight => 1.5,
   :cost => 4,
   :currency => "cp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Antitoxin (vial)",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => '',
   :cost => 50,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Crystal",
   :equipment_type_id => 1,
   :subtype => "Arcane focus",
   :weight => 1,
   :cost => 10,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Orb",
   :equipment_type_id => 1,
   :subtype => "Arcane focus",
   :weight => 3,
   :cost => 20,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Rod",
   :equipment_type_id => 1,
   :subtype => "Arcane focus",
   :weight => 2,
   :cost => 10,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Staff",
   :equipment_type_id => 1,
   :subtype => "Arcane focus",
   :weight => 4,
   :cost => 5,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Wand",
   :equipment_type_id => 1,
   :subtype => "Arcane focus",
   :weight => 1,
   :cost => 10,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Backpack",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 5,
   :cost => 2,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Ball bearings (bag of 1000)",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 2,
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Barrel",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 70,
   :cost => 2,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Basket",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 2,
   :cost => 4,
   :currency => "sp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Bedroll",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 7,
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Bell",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => '',
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Blanket",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 3,
   :cost => 5,
   :currency => "sp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Block and tackle",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 5,
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Book",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 5,
   :cost => 25,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Bottle, glass",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 2,
   :cost => 2,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Bucket",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 2,
   :cost => 5,
   :currency => "cp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Caltrops (bag of 20)",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 2,
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Candle",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => '',
   :cost => 1,
   :currency => "cp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Case, crossbow bolt",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 1,
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Case, map or scroll",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 1,
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Chain (10 feet)",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 10,
   :cost => 5,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Chalk (1 piece)",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => '',
   :cost => 1,
   :currency => "cp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Chest",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 25,
   :cost => 5,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Climber's kit",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 12,
   :cost => 25,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Clothes, common",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 3,
   :cost => 5,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Clothes, costume",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 4,
   :cost => 5,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Clothes, fine",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 6,
   :cost => 15,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Clothes, traveler's",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 4,
   :cost => 2,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Component pouch",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 2,
   :cost => 25,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Crowbar",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 5,
   :cost => 2,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Sprig of mistletoe",
   :equipment_type_id => 1,
   :subtype => "Druidic focus",
   :weight => '',
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Totem",
   :equipment_type_id => 1,
   :subtype => "Druidic focus",
   :weight => '',
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Wooden staff",
   :equipment_type_id => 1,
   :subtype => "Druidic focus",
   :weight => 4,
   :cost => 5,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Yew wand",
   :equipment_type_id => 1,
   :subtype => "Druidic focus",
   :weight => 1,
   :cost => 10,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Fishing tackle",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 4,
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Flask or tankard",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 1,
   :cost => 2,
   :currency => "cp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Grappling hook",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 4,
   :cost => 2,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Hammer",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 3,
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Hammer, sledge",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 10,
   :cost => 2,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Healer's kit",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 3,
   :cost => 5,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Amulet",
   :equipment_type_id => 1,
   :subtype => "Holy symbol",
   :weight => 1,
   :cost => 5,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Emblem",
   :equipment_type_id => 1,
   :subtype => "Holy symbol",
   :weight => '',
   :cost => 5,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Reliquary",
   :equipment_type_id => 1,
   :subtype => "Holy symbol",
   :weight => 2,
   :cost => 5,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Holy water (flask)",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 1,
   :cost => 25,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Hourglass",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 1,
   :cost => 25,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Hunting trap",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 25,
   :cost => 5,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Ink (1 ounce bottle)",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => '',
   :cost => 10,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Ink pen",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => '',
   :cost => 2,
   :currency => "cp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Jug or pitcher",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 4,
   :cost => 2,
   :currency => "cp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Ladder (10 foot)",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 25,
   :cost => 1,
   :currency => "sp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Lamp",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 1,
   :cost => 5,
   :currency => "sp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Lantern, bullseye",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 2,
   :cost => 10,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Lantern, hooded",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 2,
   :cost => 5,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Lock",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 1,
   :cost => 10,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Magnifying glass",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => '',
   :cost => 100,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Manacles",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 6,
   :cost => 2,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Mess kit",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 1,
   :cost => 2,
   :currency => "sp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Mirror, steel",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 0.5,
   :cost => 5,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Oil (flask)",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 1,
   :cost => 1,
   :currency => "sp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Paper (one sheet)",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => '',
   :cost => 2,
   :currency => "sp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Parchment (one sheet)",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => '',
   :cost => 1,
   :currency => "sp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Perfume (vial)",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => '',
   :cost => 5,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Pick, miner's",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 10,
   :cost => 2,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Piton",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 0.25,
   :cost => 5,
   :currency => "cp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Poison, basic (vial)",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => '',
   :cost => 100,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Pole (10 foot)",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 7,
   :cost => 5,
   :currency => "cp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Pot, iron",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 10,
   :cost => 2,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Potion of healing",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 0.5,
   :cost => 50,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Pouch",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 1,
   :cost => 5,
   :currency => "sp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Quiver",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 1,
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Ram, portable",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 35,
   :cost => 4,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Rations (1 day)",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 2,
   :cost => 5,
   :currency => "sp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Robes",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 4,
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Rope, hempen (50 feet)",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 10,
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Rope, silk (50 feet)",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 5,
   :cost => 10,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Sack",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 0.5,
   :cost => 1,
   :currency => "cp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Scale, merchant's",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 3,
   :cost => 5,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Sealing wax",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => '',
   :cost => 5,
   :currency => "sp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Shovel",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 5,
   :cost => 2,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Signal whistle",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => '',
   :cost => 5,
   :currency => "cp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Signet ring",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => '',
   :cost => 5,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Soap",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => '',
   :cost => 2,
   :currency => "cp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Spellbook",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 3,
   :cost => 50,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Spikes, iron (10)",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 5,
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Spyglass",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 1,
   :cost => 1000,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Tent, two-person",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 20,
   :cost => 2,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Tinderbox",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 1,
   :cost => 5,
   :currency => "sp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Torch",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 1,
   :cost => 1,
   :currency => "cp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Vial",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => '',
   :cost => 1,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Waterskin",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 5,
   :cost => 2,
   :currency => "sp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Whetstone",
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 1,
   :cost => 1,
   :currency => "cp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Vehicle, land",
   :equipment_type_id => 7,
   :subtype => "",
   :weight => '',
   :cost => '',
   :currency => "",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Vehicle, water",
   :equipment_type_id => 7,
   :subtype => "",
   :weight => '',
   :cost => '',
   :currency => "",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Carriage",
   :equipment_type_id => 7,
   :subtype => "Vehicle, land",
   :weight => 600,
   :cost => 100,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Cart",
   :equipment_type_id => 7,
   :subtype => "Vehicle, land",
   :weight => 200,
   :cost => 15,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Chariot",
   :equipment_type_id => 7,
   :subtype => "Vehicle, land",
   :weight => 100,
   :cost => 250,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Sled",
   :equipment_type_id => 7,
   :subtype => "Vehicle, land",
   :weight => 300,
   :cost => 20,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Wagon",
   :equipment_type_id => 7,
   :subtype => "Vehicle, land",
   :weight => 400,
   :cost => 25,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Galley",
   :equipment_type_id => 7,
   :subtype => "Vehicle, water",
   :weight => '',
   :cost => 30000,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Keelboat",
   :equipment_type_id => 7,
   :subtype => "Vehicle, water",
   :weight => '',
   :cost => 3000,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Longship",
   :equipment_type_id => 7,
   :subtype => "Vehicle, water",
   :weight => '',
   :cost => 10000,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Rowboat",
   :equipment_type_id => 7,
   :subtype => "Vehicle, water",
   :weight => '',
   :cost => 50,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Sailing ship",
   :equipment_type_id => 7,
   :subtype => "Vehicle, water",
   :weight => '',
   :cost => 10000,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "Warship",
   :equipment_type_id => 7,
   :subtype => "Vehicle, water",
   :weight => '',
   :cost => 25000,
   :currency => "gp",
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => 'Prayer book',
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 5,
   :cost => 25,
   :currency => 'gp',
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => 'Prayer wheel',
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 1,
   :cost => 25,
   :currency => 'gp',
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => 'Stick of incense',
   :equipment_type_id => 1,
   :subtype => "",
   :weight => '',
   :cost => 1,
   :currency => 'cp',
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => 'Vestaments',
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 4,
   :cost => 1,
   :currency => 'gp',
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => 'Belt pouch',
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 1,
   :cost => 5,
   :currency => 'sp',
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => 'Stoppered bottles filled with colored liquid',
   :equipment_type_id => 1,
   :subtype => "Tools of the con",
   :weight => 0.25,
   :cost => 'sp',
   :currency => 'sp',
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => 'Set of weighted dice',
   :equipment_type_id => 1,
   :subtype => "Tools of the con",
   :weight => '',
   :cost => 1,
   :currency => 'sp',
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => 'Deck of marked cards',
   :equipment_type_id => 1,
   :subtype => "Tools of the con",
   :weight => '',
   :cost => 5,
   :currency => 'sp',
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => 'Signet ring of an imaginary duke',
   :equipment_type_id => 1,
   :subtype => "Tools of the con",
   :weight => '',
   :cost => 5,
   :currency => 'gp',
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => 'Dark common clothes (including a hood)',
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 3,
   :cost => 5,
   :currency => 'sp',
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => 'Love letter',
   :equipment_type_id => 1,
   :subtype => "Favor of an admirer",
   :weight => '',
   :cost => '',
   :currency => '',
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => 'Lock of hair',
   :equipment_type_id => 1,
   :subtype => "Favor of an admirer",
   :weight => '',
   :cost => '',
   :currency => '',
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => 'Letter of introduction from your guild',
   :equipment_type_id => 1,
   :subtype => "",
   :weight => '',
   :cost => '',
   :currency => '',
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => 'Scroll case stuffed full of notes from your studies or prayers',
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 2,
   :cost => 2,
   :currency => 'gp',
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => 'Winter blanket',
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 3,
   :cost => 5,
   :currency => 'sp',
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => 'Scroll of pedigree',
   :equipment_type_id => 1,
   :subtype => "",
   :weight => '',
   :cost => 1,
   :currency => 'sp',
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => 'Purse',
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 1,
   :cost => 5,
   :currency => 'sp',
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => 'Trophy from an animal you killed',
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 1,
   :cost => 2,
   :currency => 'gp',
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => 'Bottle of black ink',
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 2,
   :cost => 242,
   :currency => 'gp',
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => 'Quill',
   :equipment_type_id => 1,
   :subtype => "",
   :weight => '',
   :cost => 2,
   :currency => 'sp',
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => 'Small knife',
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 1,
   :cost => 1,
   :currency => 'gp',
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => 'Letter from a dead colleage posing a question you have not been able to answer',
   :equipment_type_id => 1,
   :subtype => "",
   :weight => '',
   :cost => '',
   :currency => '',
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => 'Belaying pin (club)',
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 2,
   :cost => 1,
   :currency => 'sp',
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => 'Rabbit foot',
   :equipment_type_id => 1,
   :subtype => "Lucky charm",
   :weight => '',
   :cost => 1,
   :currency => 'gp',
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => 'Small stone with a hole in the center',
   :equipment_type_id => 1,
   :subtype => "Lucky charm",
   :weight => '',
   :cost => 1,
   :currency => 'cp',
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => 'insignia of rank',
   :equipment_type_id => 1,
   :subtype => "",
   :weight => '',
   :cost => '',
   :currency => '',
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => 'Dagger',
   :equipment_type_id => 1,
   :subtype => "Trophy taken from a fallen enemy",
   :weight => 1,
   :cost => 2,
   :currency => 'gp',
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => 'Broken blade',
   :equipment_type_id => 1,
   :subtype => "Trophy taken from a fallen enemy",
   :weight => 1,
   :cost => '',
   :currency => '',
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => 'Piece of a banner',
   :equipment_type_id => 1,
   :subtype => "Trophy taken from a fallen enemy",
   :weight => 1,
   :cost => '',
   :currency => '',
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => 'Set of bone dice',
   :equipment_type_id => 1,
   :subtype => "",
   :weight => '',
   :cost => 1,
   :currency => 'sp',
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => 'Deck of cards',
   :equipment_type_id => 1,
   :subtype => "",
   :weight => '',
   :cost => 5,
   :currency => 'sp',
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => 'Map of the city you grew up in',
   :equipment_type_id => 1,
   :subtype => "",
   :weight => '',
   :cost => 2,
   :currency => 'sp',
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => 'Pet mouse',
   :equipment_type_id => 1,
   :subtype => "",
   :weight => 0.5,
   :cost => 2,
   :currency => 'gp',
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => 'Token to remember your parents by',
   :equipment_type_id => 1,
   :subtype => "",
   :weight => '',
   :cost => '',
   :currency => '',
   :image_id => '',
   :is_public => true,
   :user_id => 1
  },
  {:name => "A mummified goblin hand",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A piece of crystal that faintly glows in the moonlight",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A gold coin minted in an unknown land",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A diary written in a language you don’t know",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A brass ring that never tarnishes",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "An old chess piece made from glass",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A pair of knucklebone dice, each with a skull symbol on the side that would normally show six pips",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A small idol depicting a nightmarish creature that gives you unsettling dreams when you sleep near it",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A rope necklace from which dangles four mummified elf fingers",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "The deed for a parcel of land in a realm unknown to you",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A 1-ounce block made from an unknown material",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A small cloth doll skewered with needles",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A tooth from an unknown beast opened",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "An enormous scale, perhaps from a dragon",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A bright green feather",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "An old divination card bearing your likeness",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A glass orb filled with moving smoke",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A 1-pound egg with a bright red shell",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A pipe that blows bubbles",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A glass jar containing a weird bit of flesh floating in pickling fluid",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A tiny gnome-crafted music box that plays a song you dimly remember from your childhood",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A small wooden statuette of a smug halfling",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A brass orb etched with strange runes",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A multicolored stone disk",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A tiny silver icon of a raven",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A bag containing forty-seven humanoid teeth, one of which is rotten",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A shard of obsidian that always feels warm to the touch",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A dragon's bony talon hanging from a plain leather necklace",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A pair of old socks",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A blank book whose pages refuse to hold ink, chalk, graphite, or any other substance for marking",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A silver badge in the shape of a five-pointed star",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A knife that belonged to a relative",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A glass vial filled with nail clippings",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A rectangular metal device with two tiny metal cups on one end that throws sparks when wet",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A white, sequined glove sized for a human",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A vest with one hundred tiny pockets",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A small, weightless stone block",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A tiny sketch portrait of a goblin",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "An empty glass vial that smells of perfume when opened",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A gemstone that looks like a lump of coal when examined by anyone but you",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A scrap of cloth from an old banner",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A rank insignia from a lost legionnaire",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A tiny silver bell without a clapper",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A mechanical canary inside a gnomish lamp",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A tiny chest carved to look like it has numerous feet on the bottom",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A dead sprite inside a clear glass bottle",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A metal can that has no opening but sounds as if it is filled with liquid, sand, spiders, or broken glass (your choice)",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A glass orb filled with water, in which swims a clockwork goldfish",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A silver spoon with an M engraved on the handle",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A whistle made from gold-colored wood",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A dead scarab beetle the size of your hand",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "Two toy soldiers, one with a missing head",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A small box filled with different-sized buttons",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A candle that can’t be lit",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A tiny cage with no door",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "An old key",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "An indecipherable treasure map",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A hilt from a broken sword",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A rabbit’s foot",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A glass eye",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A cameo carved in the likeness of a hideous person",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A silver skull the size of a coin",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "An alabaster mask",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A pyramid of sticky black incense that smells very bad",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A nightcap that, when worn, gives you pleasant dreams",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A single caltrop made from bone",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A gold monocle frame without the lens",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A 1-inch cube, each side painted a different color",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A crystal knob from a door",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A small packet filled with pink dust",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A fragment of a beautiful song, written as musical notes on two pieces of parchment",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A silver teardrop earring made from a real teardrop",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "The shell of an egg painted with scenes of human misery in disturbing detail",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A fan that, when unfolded, shows a sleeping cat",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A set of bone pipes",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A four-leaf clover pressed inside a book discussing manners and etiquette",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A sheet of parchment upon which is drawn a complex mechanical contraption",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "An ornate scabbard that fits no blade you have found so far",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "An invitation to a party where a murder happened",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A bronze pentacle with an etching of a rat's head in its center",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A purple handkerchief embroidered with the name of a powerful archmage",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "Half of a floorplan for a temple, castle, or some other structure",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A bit of folded cloth that, when unfolded, turns into a stylish cap",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A receipt of deposit at a bank in a far-flung city",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A diary with seven missing pages",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "An empty silver snuffbox bearing an inscription on the surface that says “dreams’’",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "An iron holy symbol devoted to an unknown god",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A book that tells the story of a legendary hero's rise and fall, with the last chapter missing",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A vial of dragon blood",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "An ancient arrow of elven design",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A needle that never bends",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "An ornate brooch of dwarven design",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "An empty wine bottle bearing a pretty label that says, 'The Wizard of Wines Winery, Red Dragon Crush, 331422-W'",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A mosaic tile with a multicolored, glazed surface",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A petrified mouse",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A black pirate flag adorned with a dragon's skull and crossbones",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A tiny mechanical crab or spider that moves about when it’s not being observed",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A glass jar containing lard with a label that reads, “Griffon Grease”",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A wooden box with a ceramic bottom that holds a living worm with a head on each end of its body",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  },
  {:name => "A metal urn containing the ashes of a hero",
   :equipment_type_id => 8,
   :subtype => "",
   :weight => "",
   :cost => "",
   :currency => "",
   :image_id => "",
   :is_public => true,
   :user_id => 1
  }
])
