BackgroundEquipment.create([
  {:background_id => 1,
   :equipment_choice_id => 1,
  },
  {:background_id => 1,
   :equipment_choice_id => 2,
  },
  {:background_id => 1,
   :equipment_choice_id => 3,
  },
  {:background_id => 1,
   :equipment_choice_id => 4,
  },
  {:background_id => 1,
   :equipment_choice_id => 5,
  },
  {:background_id => 1,
   :equipment_choice_id => 6,
  },
  {:background_id => 1,
   :equipment_choice_id => 7,
  },
  {:background_id => 2,
   :equipment_choice_id => 8,
  },
  {:background_id => 2,
   :equipment_choice_id => 9,
  },
  {:background_id => 2,
   :equipment_choice_id => 10,
  },
  {:background_id => 2,
   :equipment_choice_id => 11,
  },
  {:background_id => 2,
   :equipment_choice_id => 12,
  },
  {:background_id => 3,
   :equipment_choice_id => 13,
  },
  {:background_id => 3,
   :equipment_choice_id => 14,
  },
  {:background_id => 3,
   :equipment_choice_id => 15,
  },
  {:background_id => 3,
   :equipment_choice_id => 16,
  },
  {:background_id => 4,
   :equipment_choice_id => 17,
  },
  {:background_id => 4,
   :equipment_choice_id => 18,
  },
  {:background_id => 4,
   :equipment_choice_id => 19,
  },
  {:background_id => 4,
   :equipment_choice_id => 20,
  },
  {:background_id => 4,
   :equipment_choice_id => 21,
  },
  {:background_id => 5,
   :equipment_choice_id => 22,
  },
  {:background_id => 5,
   :equipment_choice_id => 23,
  },
  {:background_id => 5,
   :equipment_choice_id => 24,
  },
  {:background_id => 5,
   :equipment_choice_id => 25,
  },
  {:background_id => 5,
   :equipment_choice_id => 26,
  },
  {:background_id => 5,
   :equipment_choice_id => 27,
  },
  {:background_id => 6,
   :equipment_choice_id => 28,
  },
  {:background_id => 6,
   :equipment_choice_id => 29,
  },
  {:background_id => 6,
   :equipment_choice_id => 30,
  },
  {:background_id => 6,
   :equipment_choice_id => 31,
  },
  {:background_id => 6,
   :equipment_choice_id => 32,
  },
  {:background_id => 7,
   :equipment_choice_id => 33,
  },
  {:background_id => 7,
   :equipment_choice_id => 34,
  },
  {:background_id => 7,
   :equipment_choice_id => 35,
  },
  {:background_id => 7,
   :equipment_choice_id => 36,
  },
  {:background_id => 7,
   :equipment_choice_id => 37,
  },
  {:background_id => 8,
   :equipment_choice_id => 38,
  },
  {:background_id => 8,
   :equipment_choice_id => 39,
  },
  {:background_id => 8,
   :equipment_choice_id => 40,
  },
  {:background_id => 8,
   :equipment_choice_id => 41,
  },
  {:background_id => 8,
   :equipment_choice_id => 42,
  },
  {:background_id => 9,
   :equipment_choice_id => 43,
  },
  {:background_id => 9,
   :equipment_choice_id => 44,
  },
  {:background_id => 9,
   :equipment_choice_id => 45,
  },
  {:background_id => 9,
   :equipment_choice_id => 46,
  },
  {:background_id => 9,
   :equipment_choice_id => 47,
  },
  {:background_id => 9,
   :equipment_choice_id => 48,
  },
  {:background_id => 10,
   :equipment_choice_id => 49,
  },
  {:background_id => 10,
   :equipment_choice_id => 50,
  },
  {:background_id => 10,
   :equipment_choice_id => 51,
  },
  {:background_id => 10,
   :equipment_choice_id => 52,
  },
  {:background_id => 10,
   :equipment_choice_id => 53,
  },
  {:background_id => 10,
   :equipment_choice_id => 54,
  },
  {:background_id => 10,
   :equipment_choice_id => 55,
  },
  {:background_id => 11,
   :equipment_choice_id => 56,
  },
  {:background_id => 11,
   :equipment_choice_id => 57,
  },
  {:background_id => 11,
   :equipment_choice_id => 58,
  },
  {:background_id => 11,
   :equipment_choice_id => 59,
  },
  {:background_id => 11,
   :equipment_choice_id => 60,
  },
  {:background_id => 11,
   :equipment_choice_id => 61,
  },
  {:background_id => 12,
   :equipment_choice_id => 62,
  },
  {:background_id => 12,
   :equipment_choice_id => 63,
  },
  {:background_id => 12,
   :equipment_choice_id => 64,
  },
  {:background_id => 12,
   :equipment_choice_id => 65,
  },
  {:background_id => 12,
   :equipment_choice_id => 66,
  },
  {:background_id => 12,
   :equipment_choice_id => 67,
  },
  {:background_id => 13,
   :equipment_choice_id => 68,
  },
  {:background_id => 13,
   :equipment_choice_id => 69,
  },
  {:background_id => 13,
   :equipment_choice_id => 70,
  },
  {:background_id => 13,
   :equipment_choice_id => 71,
  },
  {:background_id => 13,
   :equipment_choice_id => 72,
  },
  {:background_id => 13,
   :equipment_choice_id => 73,
  },
  {:background_id => 13,
   :equipment_choice_id => 74,
  }
])
